// Additional framework requirements for demo purposes
// Covers: NIS2, DORA, CRA, SOC2, NSM, ISO 27701, ISO 9001, ISO 14001, ISO 45001,
// Internkontrollforskriften, Arbeidsmiljøloven, Åpenhetsloven, HMS, Bokføringsloven, Hvitvaskingsloven, CSRD

import type { ComplianceRequirement } from './complianceRequirementsData';

export const NIS2_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'nis2', requirement_id: 'nis2:art20', category: 'governance', name: 'Governance and management accountability', name_no: 'Ledelsesansvar og styring', description: 'Top management must approve cybersecurity risk management measures and oversee their implementation.', description_no: 'Toppledelsen skal godkjenne tiltak for styring av cybersikkerhetsrisiko og føre tilsyn med implementeringen.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21a', category: 'organizational', name: 'Risk analysis and information system security', name_no: 'Risikoanalyse og informasjonssystemsikkerhet', description: 'Implement policies on risk analysis and information system security.', description_no: 'Implementer retningslinjer for risikoanalyse og informasjonssystemsikkerhet.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 2 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21b', category: 'organizational', name: 'Incident handling', name_no: 'Hendelseshåndtering', description: 'Establish processes for detecting, managing, and reporting incidents.', description_no: 'Etabler prosesser for å oppdage, håndtere og rapportere hendelser.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21c', category: 'organizational', name: 'Business continuity and crisis management', name_no: 'Driftskontinuitet og krisehåndtering', description: 'Implement business continuity management including backup management and disaster recovery.', description_no: 'Implementer styring av driftskontinuitet inkludert sikkerhetskopier og gjenoppretting.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 4 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21d', category: 'organizational', name: 'Supply chain security', name_no: 'Sikkerhet i leverandørkjeden', description: 'Address security aspects of relationships with direct suppliers and service providers.', description_no: 'Ivareta sikkerhetsaspekter i relasjoner med direkte leverandører og tjenesteleverandører.', priority: 'high', domain: 'security', sla_category: 'supplier', agent_capability: 'assisted', sort_order: 5 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21e', category: 'technological', name: 'Network and information system security', name_no: 'Nettverks- og informasjonssystemsikkerhet', description: 'Security in network and information systems acquisition, development and maintenance.', description_no: 'Sikkerhet ved anskaffelse, utvikling og vedlikehold av nettverks- og informasjonssystemer.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 6 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21f', category: 'organizational', name: 'Vulnerability handling and disclosure', name_no: 'Sårbarhetsbehandling og offentliggjøring', description: 'Policies and procedures for vulnerability handling and disclosure.', description_no: 'Retningslinjer og prosedyrer for behandling og offentliggjøring av sårbarheter.', priority: 'medium', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 7 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21g', category: 'organizational', name: 'Cybersecurity risk management effectiveness', name_no: 'Vurdering av cybersikkerhetsrisikostyring', description: 'Policies and procedures to assess the effectiveness of cybersecurity risk-management measures.', description_no: 'Retningslinjer og prosedyrer for å vurdere effektiviteten av tiltak for styring av cybersikkerhetsrisiko.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 8 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21h', category: 'organizational', name: 'Cybersecurity training', name_no: 'Opplæring i cybersikkerhet', description: 'Basic cyber hygiene practices and cybersecurity training.', description_no: 'Grunnleggende cyberhygiene-praksis og opplæring i cybersikkerhet.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 9 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21i', category: 'technological', name: 'Cryptography and encryption', name_no: 'Kryptografi og kryptering', description: 'Policies and procedures for the use of cryptography and encryption.', description_no: 'Retningslinjer og prosedyrer for bruk av kryptografi og kryptering.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 10 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21j', category: 'technological', name: 'Access control and asset management', name_no: 'Tilgangskontroll og verdistyring', description: 'Human resources security, access control policies and asset management.', description_no: 'Personellsikkerhet, tilgangskontrollretningslinjer og verdistyring.', priority: 'high', domain: 'security', sla_category: 'identity_access', agent_capability: 'full', sort_order: 11 },
  { framework_id: 'nis2', requirement_id: 'nis2:art21k', category: 'technological', name: 'Multi-factor authentication', name_no: 'Flerfaktorautentisering', description: 'Use of multi-factor authentication, secured communications and emergency communication systems.', description_no: 'Bruk av flerfaktorautentisering, sikret kommunikasjon og nødkommunikasjonssystemer.', priority: 'high', domain: 'security', sla_category: 'identity_access', agent_capability: 'full', sort_order: 12 },
  { framework_id: 'nis2', requirement_id: 'nis2:art23', category: 'organizational', name: 'Incident reporting obligations', name_no: 'Plikt til hendelsesrapportering', description: 'Notify CSIRT/authority within 24h (early warning), 72h (incident notification), and 1 month (final report).', description_no: 'Varsle CSIRT/myndighet innen 24t (tidlig varsel), 72t (hendelsesvarsel) og 1 måned (sluttrapport).', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 13 },
];

export const DORA_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'dora', requirement_id: 'dora:art5', category: 'governance', name: 'ICT risk management framework', name_no: 'Rammeverk for IKT-risikostyring', description: 'Financial entities shall have a sound ICT risk management framework.', description_no: 'Finansforetak skal ha et solid rammeverk for IKT-risikostyring.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'dora', requirement_id: 'dora:art6', category: 'governance', name: 'ICT governance and organisation', name_no: 'IKT-styring og organisasjon', description: 'Management body defines and approves ICT risk management strategy.', description_no: 'Ledelsesorganet definerer og godkjenner strategien for IKT-risikostyring.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'dora', requirement_id: 'dora:art8', category: 'technological', name: 'Identification of ICT risks', name_no: 'Identifisering av IKT-risikoer', description: 'Identify, classify and document all ICT-supported business functions and information assets.', description_no: 'Identifiser, klassifiser og dokumenter alle IKT-støttede forretningsfunksjoner og informasjonsverdier.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'dora', requirement_id: 'dora:art9', category: 'technological', name: 'Protection and prevention', name_no: 'Beskyttelse og forebygging', description: 'Implement ICT security policies, procedures and controls to protect ICT systems.', description_no: 'Implementer IKT-sikkerhetspolicyer, prosedyrer og kontroller for å beskytte IKT-systemer.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 4 },
  { framework_id: 'dora', requirement_id: 'dora:art10', category: 'technological', name: 'Detection of anomalies', name_no: 'Deteksjon av avvik', description: 'Mechanisms to promptly detect anomalous activities and ICT-related incidents.', description_no: 'Mekanismer for å raskt oppdage avvikende aktiviteter og IKT-relaterte hendelser.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 5 },
  { framework_id: 'dora', requirement_id: 'dora:art11', category: 'organizational', name: 'Response and recovery', name_no: 'Respons og gjenoppretting', description: 'ICT business continuity policy and ICT response and recovery plans.', description_no: 'Retningslinjer for IKT-driftskontinuitet og planer for respons og gjenoppretting.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 6 },
  { framework_id: 'dora', requirement_id: 'dora:art17', category: 'organizational', name: 'ICT-related incident reporting', name_no: 'Rapportering av IKT-hendelser', description: 'Classify, report and notify competent authorities of major ICT-related incidents.', description_no: 'Klassifiser, rapporter og varsle myndighetene om større IKT-relaterte hendelser.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 7 },
  { framework_id: 'dora', requirement_id: 'dora:art25', category: 'organizational', name: 'Digital operational resilience testing', name_no: 'Testing av digital operasjonell motstandsdyktighet', description: 'Establish a programme for digital operational resilience testing.', description_no: 'Etabler et program for testing av digital operasjonell motstandsdyktighet.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 8 },
  { framework_id: 'dora', requirement_id: 'dora:art28', category: 'organizational', name: 'Third-party ICT risk management', name_no: 'Tredjepartsrisikostyring for IKT', description: 'Manage ICT third-party risk, including contractual arrangements with ICT providers.', description_no: 'Styr IKT-tredjepartsrisiko, inkludert kontraktsmessige ordninger med IKT-leverandører.', priority: 'high', domain: 'security', sla_category: 'supplier', agent_capability: 'assisted', sort_order: 9 },
];

export const CRA_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'cra', requirement_id: 'cra:art10', category: 'governance', name: 'Manufacturers obligations', name_no: 'Produsentens forpliktelser', description: 'Manufacturers shall ensure products with digital elements are designed and developed according to essential cybersecurity requirements.', description_no: 'Produsenter skal sikre at produkter med digitale elementer er utformet og utviklet i samsvar med grunnleggende cybersikkerhetskrav.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'cra', requirement_id: 'cra:art11', category: 'organizational', name: 'Reporting obligations', name_no: 'Rapporteringsplikt', description: 'Report actively exploited vulnerabilities and severe incidents to ENISA within 24 hours.', description_no: 'Rapporter aktivt utnyttede sårbarheter og alvorlige hendelser til ENISA innen 24 timer.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'cra', requirement_id: 'cra:annex1-1', category: 'technological', name: 'Security by design', name_no: 'Sikkerhet i design', description: 'Products shall be designed with an appropriate level of cybersecurity based on risks.', description_no: 'Produkter skal utformes med et hensiktsmessig nivå av cybersikkerhet basert på risiko.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'cra', requirement_id: 'cra:annex1-2', category: 'technological', name: 'Vulnerability handling', name_no: 'Sårbarhetshåndtering', description: 'Identify and document vulnerabilities including open-source components.', description_no: 'Identifiser og dokumenter sårbarheter inkludert åpen kildekode-komponenter.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 4 },
  { framework_id: 'cra', requirement_id: 'cra:annex1-3', category: 'technological', name: 'Secure default configuration', name_no: 'Sikker standardkonfigurasjon', description: 'Products delivered with secure default configuration and ability to reset to original state.', description_no: 'Produkter skal leveres med sikker standardkonfigurasjon og mulighet for tilbakestilling.', priority: 'medium', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 5 },
  { framework_id: 'cra', requirement_id: 'cra:annex1-4', category: 'technological', name: 'Security updates', name_no: 'Sikkerhetsoppdateringer', description: 'Ensure security updates are provided for the expected product lifetime.', description_no: 'Sørg for at sikkerhetsoppdateringer leveres i produktets forventede levetid.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 6 },
];

export const SOC2_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'soc2', requirement_id: 'soc2:cc1', category: 'governance', name: 'Control Environment', name_no: 'Kontrollmiljø', description: 'Demonstrate commitment to integrity, ethical values, and competence.', description_no: 'Demonstrer forpliktelse til integritet, etiske verdier og kompetanse.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc2', category: 'organizational', name: 'Communication and Information', name_no: 'Kommunikasjon og informasjon', description: 'Generate and use relevant quality information and communicate internally.', description_no: 'Generer og bruk relevant kvalitetsinformasjon og kommuniser internt.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 2 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc3', category: 'organizational', name: 'Risk Assessment', name_no: 'Risikovurdering', description: 'Identify and analyze risks to achieving objectives.', description_no: 'Identifiser og analyser risikoer for å nå mål.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc5', category: 'organizational', name: 'Control Activities', name_no: 'Kontrollaktiviteter', description: 'Select and develop control activities that mitigate risks.', description_no: 'Velg og utvikle kontrollaktiviteter som reduserer risiko.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc6', category: 'technological', name: 'Logical and Physical Access', name_no: 'Logisk og fysisk tilgang', description: 'Implement logical and physical access controls over information assets.', description_no: 'Implementer logisk og fysisk tilgangskontroll over informasjonsverdier.', priority: 'critical', domain: 'security', sla_category: 'identity_access', agent_capability: 'full', sort_order: 5 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc7', category: 'technological', name: 'System Operations', name_no: 'Systemdrift', description: 'Monitor system components and detect anomalies and vulnerabilities.', description_no: 'Overvåk systemkomponenter og oppdage avvik og sårbarheter.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 6 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc8', category: 'organizational', name: 'Change Management', name_no: 'Endringsstyring', description: 'Manage changes to infrastructure and software.', description_no: 'Styr endringer i infrastruktur og programvare.', priority: 'medium', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 7 },
  { framework_id: 'soc2', requirement_id: 'soc2:cc9', category: 'organizational', name: 'Risk Mitigation', name_no: 'Risikoreduksjon', description: 'Identify, select and develop risk mitigation activities.', description_no: 'Identifiser, velg og utvikle risikoreduserende aktiviteter.', priority: 'medium', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 8 },
];

export const NSM_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'nsm', requirement_id: 'nsm:id1', category: 'organizational', name: 'Kartlegg enheter og programvare', name_no: 'Kartlegg enheter og programvare', description: 'Identify and document all devices and software in the organization.', description_no: 'Identifiser og dokumenter alle enheter og programvare i organisasjonen.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 1 },
  { framework_id: 'nsm', requirement_id: 'nsm:id2', category: 'organizational', name: 'Kartlegg brukere og tilganger', name_no: 'Kartlegg brukere og tilganger', description: 'Map all users and their access rights across systems.', description_no: 'Kartlegg alle brukere og deres tilgangsrettigheter på tvers av systemer.', priority: 'critical', domain: 'security', sla_category: 'identity_access', agent_capability: 'full', sort_order: 2 },
  { framework_id: 'nsm', requirement_id: 'nsm:pr1', category: 'technological', name: 'Beskytt e-post og nettleser', name_no: 'Beskytt e-post og nettleser', description: 'Implement protections for email and web browser usage.', description_no: 'Implementer beskyttelse for e-post og nettleserbruk.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 3 },
  { framework_id: 'nsm', requirement_id: 'nsm:pr2', category: 'technological', name: 'Oppdater programvare', name_no: 'Oppdater programvare', description: 'Ensure all software is kept up to date with security patches.', description_no: 'Sørg for at all programvare er oppdatert med sikkerhetsoppdateringer.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 4 },
  { framework_id: 'nsm', requirement_id: 'nsm:pr3', category: 'technological', name: 'Aktiver sikkerhetskopier', name_no: 'Aktiver sikkerhetskopier', description: 'Implement and verify backup routines for critical data.', description_no: 'Implementer og verifiser sikkerhetskopirutiner for kritiske data.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 5 },
  { framework_id: 'nsm', requirement_id: 'nsm:pr4', category: 'technological', name: 'Herde konfigurasjoner', name_no: 'Herde konfigurasjoner', description: 'Harden configurations for all systems and devices.', description_no: 'Herd konfigurasjoner for alle systemer og enheter.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 6 },
  { framework_id: 'nsm', requirement_id: 'nsm:de1', category: 'technological', name: 'Bruk multifaktorautentisering', name_no: 'Bruk flerfaktorautentisering', description: 'Implement multi-factor authentication for all critical systems.', description_no: 'Implementer flerfaktorautentisering for alle kritiske systemer.', priority: 'critical', domain: 'security', sla_category: 'identity_access', agent_capability: 'full', sort_order: 7 },
  { framework_id: 'nsm', requirement_id: 'nsm:de2', category: 'technological', name: 'Loggfør og overvåk', name_no: 'Loggfør og overvåk', description: 'Enable logging and monitoring of network and system activities.', description_no: 'Aktiver logging og overvåking av nettverks- og systemaktiviteter.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 8 },
];

export const ISO27701_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'iso27701', requirement_id: 'iso27701:5.2', category: 'governance', name: 'PIMS-specific requirements', name_no: 'PIMS-spesifikke krav', description: 'Determine the context of the organization for privacy information management.', description_no: 'Fastslå konteksten for organisasjonen med hensyn til styring av personverninformasjon.', priority: 'critical', domain: 'privacy', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'iso27701', requirement_id: 'iso27701:6.2', category: 'organizational', name: 'PII controller conditions', name_no: 'Behandlingsansvarlig-betingelser', description: 'Determine and document legal basis, purpose and conditions for PII processing.', description_no: 'Fastslå og dokumenter rettslig grunnlag, formål og betingelser for behandling av personopplysninger.', priority: 'critical', domain: 'privacy', sla_category: 'governance', agent_capability: 'assisted', sort_order: 2 },
  { framework_id: 'iso27701', requirement_id: 'iso27701:7.2', category: 'organizational', name: 'PII processor conditions', name_no: 'Databehandlerbetingelser', description: 'Process PII only as instructed by the controller and maintain processing records.', description_no: 'Behandle personopplysninger kun etter instruks fra behandlingsansvarlig og vedlikeholde behandlingsprotokoller.', priority: 'high', domain: 'privacy', sla_category: 'governance', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'iso27701', requirement_id: 'iso27701:6.5', category: 'organizational', name: 'PII sharing and transfer', name_no: 'Deling og overføring av personopplysninger', description: 'Identify and record PII transfers and sharing, including third countries.', description_no: 'Identifiser og registrer overføringer og deling av personopplysninger, inkludert tredjeland.', priority: 'high', domain: 'privacy', sla_category: 'supplier', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'iso27701', requirement_id: 'iso27701:7.4', category: 'organizational', name: 'Privacy impact assessment', name_no: 'Personvernkonsekvensvurdering', description: 'Conduct privacy impact assessments for new processing activities.', description_no: 'Gjennomfør personvernkonsekvensvurderinger for nye behandlingsaktiviteter.', priority: 'high', domain: 'privacy', sla_category: 'governance', agent_capability: 'manual', sort_order: 5 },
];

// === "Other" category frameworks ===

export const ARBEIDSMILJOLOVEN_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§3-1', category: 'governance', name: 'Systematic HMS work', name_no: 'Krav til systematisk HMS-arbeid', description: 'The employer must establish systematic HMS work in the organization.', description_no: 'Arbeidsgiver skal sørge for at det utføres systematisk helse-, miljø- og sikkerhetsarbeid på alle plan i virksomheten.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§3-2', category: 'people', name: 'Training requirements', name_no: 'Opplæringskrav', description: 'Employer must ensure adequate training for workers in safety and health.', description_no: 'Arbeidsgiver skal sørge for at arbeidstaker som har til oppgave å lede andre, har nødvendig kompetanse for å ivareta HMS-ansvaret.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 2 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§4-1', category: 'organizational', name: 'General requirements for the working environment', name_no: 'Generelle krav til arbeidsmiljøet', description: 'The working environment shall be fully satisfactory considering worker health, safety and welfare.', description_no: 'Arbeidsmiljøet i virksomheten skal være fullt forsvarlig ut fra en enkeltvis og samlet vurdering av faktorer som kan innvirke på arbeidstakernes fysiske og psykiske helse og velferd.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 3 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§4-3', category: 'people', name: 'Psychosocial working environment', name_no: 'Krav til det psykososiale arbeidsmiljøet', description: 'Work shall be organized to preserve worker integrity and dignity.', description_no: 'Arbeidet skal legges til rette slik at arbeidstakerens integritet og verdighet ivaretas. Arbeidstaker skal ikke utsettes for trakassering eller annen utilbørlig opptreden.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 4 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§5-1', category: 'organizational', name: 'Registration and notification of injuries', name_no: 'Registrering og varsling av skader', description: 'Employer must keep records of occupational injuries and diseases.', description_no: 'Arbeidsgiver skal sørge for registrering av alle personskader som oppstår under utførelse av arbeid, og alle sykdommer som antas å ha sin grunn i arbeidet.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 5 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§6-1', category: 'governance', name: 'Safety representatives', name_no: 'Verneombud', description: 'All enterprises shall have a safety representative.', description_no: 'Ved virksomhet med 10 arbeidstakere eller mer skal det velges verneombud blant arbeidstakerne.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 6 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§7-1', category: 'governance', name: 'Working environment committee', name_no: 'Arbeidsmiljøutvalg (AMU)', description: 'Enterprises with 50+ employees shall have a working environment committee.', description_no: 'I virksomhet hvor det jevnlig sysselsettes minst 50 arbeidstakere, skal det være arbeidsmiljøutvalg.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 7 },
  { framework_id: 'arbeidsmiljoloven', requirement_id: 'aml:§10-1', category: 'organizational', name: 'Working hours', name_no: 'Arbeidstidsbestemmelser', description: 'Working hours must comply with legal limits and rest requirements.', description_no: 'Arbeidstiden skal ordnes slik at arbeidstaker ikke utsettes for uheldige fysiske eller psykiske belastninger, og at det er mulig å ivareta sikkerhetshensyn.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 8 },
];

export const APENHETSLOVEN_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'apenhetsloven', requirement_id: 'aap:§4', category: 'governance', name: 'Due diligence assessments', name_no: 'Aktsomhetsvurderinger', description: 'Conduct due diligence assessments in accordance with OECD Guidelines.', description_no: 'Virksomheten skal utføre aktsomhetsvurderinger i tråd med OECDs retningslinjer for flernasjonale selskaper.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'apenhetsloven', requirement_id: 'aap:§5', category: 'organizational', name: 'Account and report', name_no: 'Redegjørelse', description: 'Publish an annual account of due diligence assessments.', description_no: 'Virksomheten skal offentliggjøre en redegjørelse for aktsomhetsvurderingene. Redegjørelsen skal oppdateres og offentliggjøres innen 30. juni hvert år.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'apenhetsloven', requirement_id: 'aap:§6', category: 'organizational', name: 'Right to information', name_no: 'Rett til informasjon', description: 'Anyone has the right to request information about how the enterprise handles impacts.', description_no: 'Enhver har ved skriftlig forespørsel rett på informasjon fra en virksomhet om hvordan virksomheten håndterer faktiske og potensielle negative konsekvenser.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'apenhetsloven', requirement_id: 'aap:§4a', category: 'organizational', name: 'Map and assess negative impacts', name_no: 'Kartlegg og vurder negative konsekvenser', description: 'Map actual and potential adverse impacts on human rights and decent working conditions.', description_no: 'Kartlegge og vurdere faktiske og potensielle negative konsekvenser for grunnleggende menneskerettigheter og anstendige arbeidsforhold.', priority: 'high', domain: 'security', sla_category: 'supplier', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'apenhetsloven', requirement_id: 'aap:§4b', category: 'organizational', name: 'Implement measures', name_no: 'Iverksett tiltak', description: 'Implement appropriate measures to cease, prevent or mitigate adverse impacts.', description_no: 'Iverksette egnede tiltak for å stanse, forebygge eller begrense negative konsekvenser.', priority: 'high', domain: 'security', sla_category: 'supplier', agent_capability: 'manual', sort_order: 5 },
  { framework_id: 'apenhetsloven', requirement_id: 'aap:§4c', category: 'organizational', name: 'Monitor implementation', name_no: 'Følg opp tiltak', description: 'Follow up and monitor implementation and results of measures.', description_no: 'Følge med på gjennomføring og resultater av tiltak.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 6 },
];

export const HMS_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'hms', requirement_id: 'hms:§1', category: 'governance', name: 'Systematic HMS', name_no: 'Systematisk HMS-arbeid', description: 'Establish and maintain systematic health, environment and safety work.', description_no: 'Virksomheten skal etablere og vedlikeholde systematisk helse-, miljø- og sikkerhetsarbeid.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'hms', requirement_id: 'hms:§2', category: 'governance', name: 'HMS goals', name_no: 'HMS-mål', description: 'Establish goals for HMS work in the organization.', description_no: 'Fastsette mål for helse, miljø og sikkerhet.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'hms', requirement_id: 'hms:§3', category: 'organizational', name: 'Overview of regulations', name_no: 'Oversikt over krav', description: 'Maintain an overview of applicable laws and regulations.', description_no: 'Ha oversikt over virksomhetens organisasjon, herunder hvordan ansvar, oppgaver og myndighet for arbeidet med helse, miljø og sikkerhet er fordelt.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'hms', requirement_id: 'hms:§4', category: 'organizational', name: 'Risk assessment', name_no: 'Risikovurdering', description: 'Identify hazards, assess risks and plan measures.', description_no: 'Kartlegge farer og problemer og på denne bakgrunn vurdere risiko, samt utarbeide tilhørende planer og tiltak for å redusere risikoforholdene.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'hms', requirement_id: 'hms:§5', category: 'organizational', name: 'Deviation handling', name_no: 'Avvikshåndtering', description: 'Implement routines for detecting, correcting and preventing non-conformities.', description_no: 'Iverksette rutiner for å avdekke, rette opp og forebygge overtredelser av krav fastsatt i eller i medhold av helse-, miljø- og sikkerhetslovgivningen.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 5 },
  { framework_id: 'hms', requirement_id: 'hms:§6', category: 'organizational', name: 'Management review', name_no: 'Ledelsens gjennomgang', description: 'Management shall regularly review the HMS system.', description_no: 'Foreta systematisk overvåking og gjennomgang av internkontrollen for å sikre at den fungerer som forutsatt.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 6 },
];

export const INTERNKONTROLL_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'internkontroll', requirement_id: 'ik:§5-1', category: 'governance', name: 'Establish internal control', name_no: 'Etablere internkontroll', description: 'The responsible person shall establish a systematic internal control system.', description_no: 'Den ansvarlige skal sørge for at det innføres og utøves internkontroll i virksomheten.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'internkontroll', requirement_id: 'ik:§5-2', category: 'governance', name: 'HMS goals and targets', name_no: 'Mål for HMS', description: 'Set goals for health, environment and safety.', description_no: 'Fastsette mål for helse, miljø og sikkerhet.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'internkontroll', requirement_id: 'ik:§5-3', category: 'organizational', name: 'Organizational overview', name_no: 'Organisasjonsoversikt', description: 'Overview of how responsibilities are distributed for HMS.', description_no: 'Ha oversikt over virksomhetens organisasjon, herunder hvordan ansvar, oppgaver og myndighet for HMS-arbeidet er fordelt.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'internkontroll', requirement_id: 'ik:§5-4', category: 'organizational', name: 'Risk assessment and mapping', name_no: 'Kartlegging og risikovurdering', description: 'Map hazards and assess risks, create plans and measures.', description_no: 'Kartlegge farer og problemer og på denne bakgrunn vurdere risiko, samt utarbeide tilhørende planer og tiltak for å redusere risikoforholdene.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'internkontroll', requirement_id: 'ik:§5-5', category: 'organizational', name: 'Deviation routines', name_no: 'Avviksrutiner', description: 'Establish routines for detecting, correcting and preventing deviations.', description_no: 'Iverksette rutiner for å avdekke, rette opp og forebygge overtredelser av krav.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 5 },
  { framework_id: 'internkontroll', requirement_id: 'ik:§5-6', category: 'governance', name: 'Systematic review', name_no: 'Systematisk gjennomgang', description: 'Conduct systematic monitoring and review of the internal control system.', description_no: 'Foreta systematisk overvåking og gjennomgang av internkontrollen for å sikre at den fungerer som forutsatt.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 6 },
];

export const BOKFORINGSLOVEN_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'bokforingsloven', requirement_id: 'bok:§5', category: 'governance', name: 'Bookkeeping obligation', name_no: 'Bokføringsplikt', description: 'Maintain bookkeeping in accordance with generally accepted accounting principles.', description_no: 'Bokføringspliktige skal ha bokføring i samsvar med god bokføringsskikk.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'bokforingsloven', requirement_id: 'bok:§10', category: 'organizational', name: 'Documentation requirements', name_no: 'Dokumentasjonskrav', description: 'All transactions must be documented with vouchers.', description_no: 'Alle transaksjoner skal være dokumentert med bilag.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'bokforingsloven', requirement_id: 'bok:§13', category: 'organizational', name: 'Retention requirements', name_no: 'Oppbevaringskrav', description: 'Accounting records must be retained for a minimum of 5 years.', description_no: 'Regnskapsmateriale skal oppbevares i minst 5 år etter regnskapsårets slutt.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'bokforingsloven', requirement_id: 'bok:§13a', category: 'technological', name: 'Electronic storage security', name_no: 'Sikkerhet ved elektronisk oppbevaring', description: 'Electronic accounting records must be stored securely against loss and unauthorized access.', description_no: 'Elektronisk regnskapsmateriale skal oppbevares sikkert mot tap og uautorisert tilgang.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'full', sort_order: 4 },
];

export const HVITVASKINGSLOVEN_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'hvitvasking', requirement_id: 'hvit:§6', category: 'governance', name: 'Risk assessment', name_no: 'Risikovurdering', description: 'Conduct risk assessment of money laundering and terrorist financing exposure.', description_no: 'Rapporteringspliktige skal identifisere og vurdere risikoen for hvitvasking og terrorfinansiering.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'hvitvasking', requirement_id: 'hvit:§7', category: 'governance', name: 'Internal routines', name_no: 'Interne rutiner', description: 'Establish internal policies, procedures and controls for AML.', description_no: 'Rapporteringspliktige skal ha oppdaterte interne rutiner for å sikre at forpliktelsene etter loven oppfylles.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'hvitvasking', requirement_id: 'hvit:§10', category: 'organizational', name: 'Customer due diligence', name_no: 'Kundetiltak', description: 'Implement customer due diligence measures including identification and verification.', description_no: 'Rapporteringspliktige skal gjennomføre kundetiltak, herunder identifisering og bekreftelse av kundens identitet.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'hvitvasking', requirement_id: 'hvit:§26', category: 'organizational', name: 'Reporting obligations', name_no: 'Rapporteringsplikt', description: 'Report suspicious transactions to the Financial Intelligence Unit.', description_no: 'Rapporteringspliktige skal undersøke og rapportere mistenkelige transaksjoner til Økokrim.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 4 },
  { framework_id: 'hvitvasking', requirement_id: 'hvit:§36', category: 'people', name: 'Training', name_no: 'Opplæring', description: 'Ensure relevant employees receive adequate AML/CFT training.', description_no: 'Rapporteringspliktige skal sørge for at ansatte gis nødvendig opplæring.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 5 },
];

export const ISO9001_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'iso9001', requirement_id: 'iso9001:4.1', category: 'governance', name: 'Context of the organization', name_no: 'Organisasjonens kontekst', description: 'Determine external and internal issues relevant to quality management.', description_no: 'Fastslå eksterne og interne forhold som er relevante for kvalitetsstyringen.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'iso9001', requirement_id: 'iso9001:5.1', category: 'governance', name: 'Leadership commitment', name_no: 'Ledelsens forpliktelse', description: 'Top management shall demonstrate leadership and commitment.', description_no: 'Toppledelsen skal demonstrere lederskap og forpliktelse med hensyn til kvalitetsstyringssystemet.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'iso9001', requirement_id: 'iso9001:6.1', category: 'organizational', name: 'Actions to address risks', name_no: 'Tiltak for å håndtere risikoer', description: 'Plan actions to address risks and opportunities.', description_no: 'Planlegg tiltak for å håndtere risikoer og muligheter.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'iso9001', requirement_id: 'iso9001:7.5', category: 'organizational', name: 'Documented information', name_no: 'Dokumentert informasjon', description: 'Create, update and control documented information required by the QMS.', description_no: 'Opprette, oppdatere og kontrollere dokumentert informasjon som kreves av kvalitetsstyringssystemet.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'iso9001', requirement_id: 'iso9001:8.1', category: 'organizational', name: 'Operational planning and control', name_no: 'Driftsplanlegging og -kontroll', description: 'Plan, implement and control processes needed to meet requirements.', description_no: 'Planlegge, implementere og kontrollere prosessene som kreves for å oppfylle krav.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 5 },
  { framework_id: 'iso9001', requirement_id: 'iso9001:9.1', category: 'organizational', name: 'Monitoring and measurement', name_no: 'Overvåking og måling', description: 'Determine what needs to be monitored and measured for the QMS.', description_no: 'Fastsette hva som skal overvåkes og måles for kvalitetsstyringssystemet.', priority: 'medium', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 6 },
  { framework_id: 'iso9001', requirement_id: 'iso9001:10.1', category: 'organizational', name: 'Continual improvement', name_no: 'Kontinuerlig forbedring', description: 'Determine and select opportunities for improvement.', description_no: 'Fastslå og velge muligheter for forbedring og iverksette nødvendige tiltak.', priority: 'medium', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 7 },
];

export const ISO14001_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'iso14001', requirement_id: 'iso14001:4.1', category: 'governance', name: 'Context of the organization', name_no: 'Organisasjonens kontekst', description: 'Determine environmental issues relevant to the organization.', description_no: 'Fastslå miljøforhold som er relevante for organisasjonen.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'iso14001', requirement_id: 'iso14001:6.1', category: 'organizational', name: 'Environmental aspects', name_no: 'Miljøaspekter', description: 'Identify environmental aspects and determine significant impacts.', description_no: 'Identifiser miljøaspekter og fastslå vesentlige miljøpåvirkninger.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 2 },
  { framework_id: 'iso14001', requirement_id: 'iso14001:6.2', category: 'governance', name: 'Environmental objectives', name_no: 'Miljømål', description: 'Establish environmental objectives at relevant functions and levels.', description_no: 'Etablere miljømål for relevante funksjoner og nivåer.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 3 },
  { framework_id: 'iso14001', requirement_id: 'iso14001:8.1', category: 'organizational', name: 'Operational planning', name_no: 'Driftsplanlegging', description: 'Plan and control processes to meet environmental management system requirements.', description_no: 'Planlegge og kontrollere prosesser for å oppfylle krav i miljøstyringssystemet.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'iso14001', requirement_id: 'iso14001:8.2', category: 'organizational', name: 'Emergency preparedness', name_no: 'Beredskap og respons', description: 'Establish processes for responding to potential emergency situations.', description_no: 'Etablere prosesser for respons på potensielle nødsituasjoner.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 5 },
];

export const ISO45001_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'iso45001', requirement_id: 'iso45001:5.1', category: 'governance', name: 'Leadership commitment OHS', name_no: 'Ledelsens forpliktelse for HMS', description: 'Top management shall demonstrate leadership for the OH&S management system.', description_no: 'Toppledelsen skal demonstrere lederskap for styringssystemet for arbeidshelse og -sikkerhet.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'iso45001', requirement_id: 'iso45001:5.4', category: 'governance', name: 'Worker participation', name_no: 'Arbeidstakermedvirkning', description: 'Ensure consultation and participation of workers and representatives.', description_no: 'Sikre konsultasjon og deltakelse av arbeidstakere og deres representanter.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'iso45001', requirement_id: 'iso45001:6.1', category: 'organizational', name: 'Hazard identification', name_no: 'Identifisering av farer', description: 'Establish processes for hazard identification and assessment of OH&S risks.', description_no: 'Etablere prosesser for identifisering av farer og vurdering av HMS-risikoer.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 3 },
  { framework_id: 'iso45001', requirement_id: 'iso45001:8.1', category: 'organizational', name: 'Eliminate hazards', name_no: 'Eliminere farer', description: 'Establish processes to eliminate hazards and reduce OH&S risks.', description_no: 'Etablere prosesser for å eliminere farer og redusere HMS-risikoer.', priority: 'critical', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 4 },
  { framework_id: 'iso45001', requirement_id: 'iso45001:8.2', category: 'organizational', name: 'Emergency preparedness OHS', name_no: 'Beredskap for HMS', description: 'Identify and plan for potential emergency situations.', description_no: 'Identifisere og planlegge for potensielle nødsituasjoner.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'manual', sort_order: 5 },
  { framework_id: 'iso45001', requirement_id: 'iso45001:10.2', category: 'organizational', name: 'Incident investigation', name_no: 'Hendelsesundersøkelse', description: 'Determine processes for reporting, investigating and taking action on incidents.', description_no: 'Fastsette prosesser for rapportering, undersøkelse og iverksetting av tiltak ved hendelser.', priority: 'high', domain: 'security', sla_category: 'operations', agent_capability: 'assisted', sort_order: 6 },
];

export const CSRD_REQUIREMENTS: ComplianceRequirement[] = [
  { framework_id: 'csrd', requirement_id: 'csrd:e1', category: 'governance', name: 'Climate change', name_no: 'Klimaendringer', description: 'Disclose climate-related risks, targets and transition plans.', description_no: 'Rapporter klimarelaterte risikoer, mål og omstillingsplaner.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 1 },
  { framework_id: 'csrd', requirement_id: 'csrd:s1', category: 'people', name: 'Own workforce', name_no: 'Egen arbeidsstyrke', description: 'Report on working conditions, equal treatment and other work-related rights.', description_no: 'Rapporter om arbeidsforhold, likebehandling og andre arbeidsrelaterte rettigheter.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 2 },
  { framework_id: 'csrd', requirement_id: 'csrd:s2', category: 'organizational', name: 'Value chain workers', name_no: 'Arbeidere i verdikjeden', description: 'Report on human rights and working conditions in the value chain.', description_no: 'Rapporter om menneskerettigheter og arbeidsforhold i verdikjeden.', priority: 'high', domain: 'security', sla_category: 'supplier', agent_capability: 'manual', sort_order: 3 },
  { framework_id: 'csrd', requirement_id: 'csrd:g1', category: 'governance', name: 'Business conduct', name_no: 'Forretningsatferd', description: 'Report on corporate culture, anti-corruption and responsible business conduct.', description_no: 'Rapporter om bedriftskultur, antikorrupsjon og ansvarlig forretningsatferd.', priority: 'high', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 4 },
  { framework_id: 'csrd', requirement_id: 'csrd:drm', category: 'governance', name: 'Double materiality assessment', name_no: 'Dobbel vesentlighetsanalyse', description: 'Conduct double materiality assessment considering impact and financial materiality.', description_no: 'Gjennomfør dobbel vesentlighetsanalyse som vurderer både påvirkning og finansiell vesentlighet.', priority: 'critical', domain: 'security', sla_category: 'governance', agent_capability: 'manual', sort_order: 5 },
];

// Aggregate all additional requirements
export const ALL_ADDITIONAL_REQUIREMENTS: ComplianceRequirement[] = [
  ...NIS2_REQUIREMENTS,
  ...DORA_REQUIREMENTS,
  ...CRA_REQUIREMENTS,
  ...SOC2_REQUIREMENTS,
  ...NSM_REQUIREMENTS,
  ...ISO27701_REQUIREMENTS,
  ...ARBEIDSMILJOLOVEN_REQUIREMENTS,
  ...APENHETSLOVEN_REQUIREMENTS,
  ...HMS_REQUIREMENTS,
  ...INTERNKONTROLL_REQUIREMENTS,
  ...BOKFORINGSLOVEN_REQUIREMENTS,
  ...HVITVASKINGSLOVEN_REQUIREMENTS,
  ...ISO9001_REQUIREMENTS,
  ...ISO14001_REQUIREMENTS,
  ...ISO45001_REQUIREMENTS,
  ...CSRD_REQUIREMENTS,
];

// Helper to get requirements for any framework (combines both files)
export function getAllRequirementsForFramework(frameworkId: string): ComplianceRequirement[] {
  // First check additional requirements
  const additional = ALL_ADDITIONAL_REQUIREMENTS.filter(r => r.framework_id === frameworkId);
  if (additional.length > 0) return additional;
  // Fallback to main data (imported by consumer)
  return [];
}
