// Compliance Requirements Data for ISO 27001:2022, GDPR, and AI Act
// This file contains the master list of all compliance requirements

export type AgentCapability = 'full' | 'assisted' | 'manual';
export type RequirementPriority = 'critical' | 'high' | 'medium' | 'low';
export type RequirementDomain = 'privacy' | 'security' | 'ai';
export type RequirementCategory = 'organizational' | 'people' | 'physical' | 'technological' | 'legal' | 'governance';

export interface ComplianceRequirement {
  framework_id: string;
  requirement_id: string;
  category: RequirementCategory;
  name: string;
  name_no: string;
  description: string;
  description_no: string;
  priority: RequirementPriority;
  domain: RequirementDomain;
  sla_category?: string;
  agent_capability: AgentCapability;
  sort_order: number;
}

// ============================================
// ISO 27001:2022 - 93 Controls (Annex A)
// ============================================

export const ISO27001_CONTROLS: ComplianceRequirement[] = [
  // A.5 Organizational Controls (37 controls)
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.1',
    category: 'organizational',
    name: 'Policies for information security',
    name_no: 'Retningslinjer for informasjonssikkerhet',
    description: 'Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties.',
    description_no: 'Retningslinjer for informasjonssikkerhet og tematiske retningslinjer skal defineres, godkjennes av ledelsen, publiseres, kommuniseres til og bekreftes av relevant personell og relevante interessenter.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'full',
    sort_order: 1
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.2',
    category: 'organizational',
    name: 'Information security roles and responsibilities',
    name_no: 'Roller og ansvar for informasjonssikkerhet',
    description: 'Information security roles and responsibilities shall be defined and allocated according to the organization needs.',
    description_no: 'Roller og ansvar for informasjonssikkerhet skal defineres og tildeles i henhold til organisasjonens behov.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'assisted',
    sort_order: 2
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.3',
    category: 'organizational',
    name: 'Segregation of duties',
    name_no: 'Funksjonsadskillelse',
    description: 'Conflicting duties and conflicting areas of responsibility shall be segregated.',
    description_no: 'Motstridende plikter og motstridende ansvarsområder skal adskilles.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'assisted',
    sort_order: 3
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.4',
    category: 'organizational',
    name: 'Management responsibilities',
    name_no: 'Ledelsesansvar',
    description: 'Management shall require all personnel to apply information security in accordance with the established information security policy.',
    description_no: 'Ledelsen skal kreve at alt personell anvender informasjonssikkerhet i samsvar med den etablerte informasjonssikkerhetspolicyen.',
    priority: 'high',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 4
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.5',
    category: 'organizational',
    name: 'Contact with authorities',
    name_no: 'Kontakt med myndigheter',
    description: 'The organization shall establish and maintain contact with relevant authorities.',
    description_no: 'Organisasjonen skal etablere og vedlikeholde kontakt med relevante myndigheter.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 5
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.6',
    category: 'organizational',
    name: 'Contact with special interest groups',
    name_no: 'Kontakt med interessegrupper',
    description: 'The organization shall establish and maintain contact with special interest groups or other specialist security forums.',
    description_no: 'Organisasjonen skal etablere og vedlikeholde kontakt med spesielle interessegrupper eller andre spesialistfora for sikkerhet.',
    priority: 'low',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 6
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.7',
    category: 'organizational',
    name: 'Threat intelligence',
    name_no: 'Trusseletterretning',
    description: 'Information relating to information security threats shall be collected and analysed to produce threat intelligence.',
    description_no: 'Informasjon relatert til informasjonssikkerhetstrusler skal samles inn og analyseres for å produsere trusseletterretning.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 7
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.8',
    category: 'organizational',
    name: 'Information security in project management',
    name_no: 'Informasjonssikkerhet i prosjektledelse',
    description: 'Information security shall be integrated into project management.',
    description_no: 'Informasjonssikkerhet skal integreres i prosjektledelse.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 8
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.9',
    category: 'organizational',
    name: 'Inventory of information and other associated assets',
    name_no: 'Oversikt over informasjon og tilknyttede eiendeler',
    description: 'An inventory of information and other associated assets, including owners, shall be developed and maintained.',
    description_no: 'En oversikt over informasjon og andre tilknyttede eiendeler, inkludert eiere, skal utvikles og vedlikeholdes.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 9
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.10',
    category: 'organizational',
    name: 'Acceptable use of information and other associated assets',
    name_no: 'Akseptabel bruk av informasjon og eiendeler',
    description: 'Rules for the acceptable use of information and other associated assets shall be identified, documented and implemented.',
    description_no: 'Regler for akseptabel bruk av informasjon og andre tilknyttede eiendeler skal identifiseres, dokumenteres og implementeres.',
    priority: 'high',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'full',
    sort_order: 10
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.11',
    category: 'organizational',
    name: 'Return of assets',
    name_no: 'Retur av eiendeler',
    description: 'Personnel and other interested parties as appropriate shall return all the organizational assets in their possession upon change or termination of their employment, contract or agreement.',
    description_no: 'Personell og andre interessenter skal returnere alle organisasjonens eiendeler i deres besittelse ved endring eller avslutning av deres ansettelse, kontrakt eller avtale.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'assisted',
    sort_order: 11
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.12',
    category: 'organizational',
    name: 'Classification of information',
    name_no: 'Klassifisering av informasjon',
    description: 'Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.',
    description_no: 'Informasjon skal klassifiseres i henhold til organisasjonens informasjonssikkerhetsbehov basert på konfidensialitet, integritet, tilgjengelighet og relevante krav fra interessenter.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 12
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.13',
    category: 'organizational',
    name: 'Labelling of information',
    name_no: 'Merking av informasjon',
    description: 'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
    description_no: 'Et passende sett med prosedyrer for merking av informasjon skal utvikles og implementeres i samsvar med informasjonsklassifiseringsskjemaet som er vedtatt av organisasjonen.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 13
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.14',
    category: 'organizational',
    name: 'Information transfer',
    name_no: 'Informasjonsoverføring',
    description: 'Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.',
    description_no: 'Regler, prosedyrer eller avtaler for informasjonsoverføring skal være på plass for alle typer overføringsfasiliteter innenfor organisasjonen og mellom organisasjonen og andre parter.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 14
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.15',
    category: 'organizational',
    name: 'Access control',
    name_no: 'Tilgangskontroll',
    description: 'Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.',
    description_no: 'Regler for å kontrollere fysisk og logisk tilgang til informasjon og andre tilknyttede eiendeler skal etableres og implementeres basert på forretnings- og informasjonssikkerhetskrav.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 15
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.16',
    category: 'organizational',
    name: 'Identity management',
    name_no: 'Identitetsadministrasjon',
    description: 'The full life cycle of identities shall be managed.',
    description_no: 'Hele livssyklusen til identiteter skal administreres.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 16
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.17',
    category: 'organizational',
    name: 'Authentication information',
    name_no: 'Autentiseringsinformasjon',
    description: 'Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.',
    description_no: 'Tildeling og administrasjon av autentiseringsinformasjon skal kontrolleres av en administrasjonsprosess, inkludert rådgivning til personell om hensiktsmessig håndtering av autentiseringsinformasjon.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 17
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.18',
    category: 'organizational',
    name: 'Access rights',
    name_no: 'Tilgangsrettigheter',
    description: 'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization\'s topic-specific policy on and rules for access control.',
    description_no: 'Tilgangsrettigheter til informasjon og andre tilknyttede eiendeler skal tildeles, gjennomgås, endres og fjernes i samsvar med organisasjonens tematiske policy og regler for tilgangskontroll.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 18
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.19',
    category: 'organizational',
    name: 'Information security in supplier relationships',
    name_no: 'Informasjonssikkerhet i leverandørforhold',
    description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier\'s products or services.',
    description_no: 'Prosesser og prosedyrer skal defineres og implementeres for å håndtere informasjonssikkerhetsrisikoer forbundet med bruk av leverandørers produkter eller tjenester.',
    priority: 'high',
    domain: 'security',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'full',
    sort_order: 19
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.20',
    category: 'organizational',
    name: 'Addressing information security within supplier agreements',
    name_no: 'Adressering av informasjonssikkerhet i leverandøravtaler',
    description: 'Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.',
    description_no: 'Relevante informasjonssikkerhetskrav skal etableres og avtales med hver leverandør basert på typen leverandørforhold.',
    priority: 'high',
    domain: 'security',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'assisted',
    sort_order: 20
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.21',
    category: 'organizational',
    name: 'Managing information security in the ICT supply chain',
    name_no: 'Administrasjon av informasjonssikkerhet i IKT-leverandørkjeden',
    description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.',
    description_no: 'Prosesser og prosedyrer skal defineres og implementeres for å håndtere informasjonssikkerhetsrisikoer forbundet med leverandørkjeden for IKT-produkter og -tjenester.',
    priority: 'high',
    domain: 'security',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'full',
    sort_order: 21
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.22',
    category: 'organizational',
    name: 'Monitoring, review and change management of supplier services',
    name_no: 'Overvåking, gjennomgang og endringsstyring av leverandørtjenester',
    description: 'The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.',
    description_no: 'Organisasjonen skal regelmessig overvåke, gjennomgå, evaluere og administrere endringer i leverandørers informasjonssikkerhetspraksis og tjenesteleveranse.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'full',
    sort_order: 22
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.23',
    category: 'organizational',
    name: 'Information security for use of cloud services',
    name_no: 'Informasjonssikkerhet for bruk av skytjenester',
    description: 'Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization\'s information security requirements.',
    description_no: 'Prosesser for anskaffelse, bruk, administrasjon og avslutning av skytjenester skal etableres i samsvar med organisasjonens informasjonssikkerhetskrav.',
    priority: 'high',
    domain: 'security',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'full',
    sort_order: 23
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.24',
    category: 'organizational',
    name: 'Information security incident management planning and preparation',
    name_no: 'Planlegging og forberedelse av hendelseshåndtering',
    description: 'The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.',
    description_no: 'Organisasjonen skal planlegge og forberede seg på håndtering av informasjonssikkerhetshendelser ved å definere, etablere og kommunisere prosesser, roller og ansvar for hendelseshåndtering.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 24
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.25',
    category: 'organizational',
    name: 'Assessment and decision on information security events',
    name_no: 'Vurdering og beslutning om sikkerhetshendelser',
    description: 'The organization shall assess information security events and decide if they are to be categorized as information security incidents.',
    description_no: 'Organisasjonen skal vurdere informasjonssikkerhetshendelser og beslutte om de skal kategoriseres som informasjonssikkerhetsincidenter.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 25
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.26',
    category: 'organizational',
    name: 'Response to information security incidents',
    name_no: 'Respons på sikkerhetshendelser',
    description: 'Information security incidents shall be responded to in accordance with the documented procedures.',
    description_no: 'Informasjonssikkerhetshendelser skal håndteres i samsvar med dokumenterte prosedyrer.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 26
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.27',
    category: 'organizational',
    name: 'Learning from information security incidents',
    name_no: 'Læring fra sikkerhetshendelser',
    description: 'Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.',
    description_no: 'Kunnskap fra informasjonssikkerhetshendelser skal brukes til å styrke og forbedre informasjonssikkerhetskontrollene.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 27
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.28',
    category: 'organizational',
    name: 'Collection of evidence',
    name_no: 'Innsamling av bevis',
    description: 'The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.',
    description_no: 'Organisasjonen skal etablere og implementere prosedyrer for identifikasjon, innsamling, anskaffelse og bevaring av bevis relatert til informasjonssikkerhetshendelser.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 28
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.29',
    category: 'organizational',
    name: 'Information security during disruption',
    name_no: 'Informasjonssikkerhet under forstyrrelser',
    description: 'The organization shall plan how to maintain information security at an appropriate level during disruption.',
    description_no: 'Organisasjonen skal planlegge hvordan informasjonssikkerhet skal opprettholdes på et passende nivå under forstyrrelser.',
    priority: 'high',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 29
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.30',
    category: 'organizational',
    name: 'ICT readiness for business continuity',
    name_no: 'IKT-beredskap for forretningskontinuitet',
    description: 'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.',
    description_no: 'IKT-beredskap skal planlegges, implementeres, vedlikeholdes og testes basert på forretningskontinuitetsmål og IKT-kontinuitetskrav.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 30
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.31',
    category: 'organizational',
    name: 'Legal, statutory, regulatory and contractual requirements',
    name_no: 'Juridiske, lovpålagte og kontraktsmessige krav',
    description: 'Legal, statutory, regulatory and contractual requirements relevant to information security and the organization\'s approach to meet these requirements shall be identified, documented and kept up to date.',
    description_no: 'Juridiske, lovpålagte, regulatoriske og kontraktsmessige krav som er relevante for informasjonssikkerhet, og organisasjonens tilnærming til å oppfylle disse kravene, skal identifiseres, dokumenteres og holdes oppdatert.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'full',
    sort_order: 31
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.32',
    category: 'organizational',
    name: 'Intellectual property rights',
    name_no: 'Immaterielle rettigheter',
    description: 'The organization shall implement appropriate procedures to protect intellectual property rights.',
    description_no: 'Organisasjonen skal implementere passende prosedyrer for å beskytte immaterielle rettigheter.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 32
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.33',
    category: 'organizational',
    name: 'Protection of records',
    name_no: 'Beskyttelse av arkiver',
    description: 'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.',
    description_no: 'Arkiver skal beskyttes mot tap, ødeleggelse, forfalskning, uautorisert tilgang og uautorisert utgivelse.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 33
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.34',
    category: 'organizational',
    name: 'Privacy and protection of personal information',
    name_no: 'Personvern og beskyttelse av personopplysninger',
    description: 'The organization shall identify and meet the requirements regarding the preservation of privacy and protection of personal information according to applicable laws, regulations and contractual requirements.',
    description_no: 'Organisasjonen skal identifisere og oppfylle krav angående bevaring av personvern og beskyttelse av personopplysninger i henhold til gjeldende lover, forskrifter og kontraktsmessige krav.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'full',
    sort_order: 34
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.35',
    category: 'organizational',
    name: 'Independent review of information security',
    name_no: 'Uavhengig gjennomgang av informasjonssikkerhet',
    description: 'The organization\'s approach to managing information security and its implementation shall be reviewed independently at planned intervals or when significant changes occur.',
    description_no: 'Organisasjonens tilnærming til å administrere informasjonssikkerhet og implementeringen av denne skal gjennomgås uavhengig med planlagte intervaller eller når betydelige endringer skjer.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 35
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.36',
    category: 'organizational',
    name: 'Compliance with policies, rules and standards for information security',
    name_no: 'Samsvar med policyer, regler og standarder',
    description: 'Compliance with the organization\'s information security policy, topic-specific policies, rules and standards shall be regularly reviewed.',
    description_no: 'Samsvar med organisasjonens informasjonssikkerhetspolicy, tematiske policyer, regler og standarder skal gjennomgås regelmessig.',
    priority: 'high',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'full',
    sort_order: 36
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.5.37',
    category: 'organizational',
    name: 'Documented operating procedures',
    name_no: 'Dokumenterte driftsprosedyrer',
    description: 'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.',
    description_no: 'Driftsprosedyrer for informasjonsbehandlingsfasiliteter skal dokumenteres og gjøres tilgjengelige for personell som trenger dem.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 37
  },

  // A.6 People Controls (8 controls)
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.1',
    category: 'people',
    name: 'Screening',
    name_no: 'Bakgrunnssjekk',
    description: 'Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis.',
    description_no: 'Bakgrunnsverifiseringskontroller på alle kandidater som skal bli personell, skal gjennomføres før de begynner i organisasjonen og på løpende basis.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'manual',
    sort_order: 38
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.2',
    category: 'people',
    name: 'Terms and conditions of employment',
    name_no: 'Ansettelsesvilkår',
    description: 'The employment contractual agreements shall state the personnel\'s and the organization\'s responsibilities for information security.',
    description_no: 'Ansettelseskontraktsavtaler skal angi personellets og organisasjonens ansvar for informasjonssikkerhet.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'assisted',
    sort_order: 39
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.3',
    category: 'people',
    name: 'Information security awareness, education and training',
    name_no: 'Bevissthet, opplæring og trening i informasjonssikkerhet',
    description: 'Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization\'s information security policy.',
    description_no: 'Personell i organisasjonen og relevante interessenter skal motta passende bevissthet, utdanning og opplæring i informasjonssikkerhet og regelmessige oppdateringer av organisasjonens informasjonssikkerhetspolicy.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'manual',
    sort_order: 40
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.4',
    category: 'people',
    name: 'Disciplinary process',
    name_no: 'Disiplinærprosess',
    description: 'A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.',
    description_no: 'En disiplinærprosess skal formaliseres og kommuniseres for å iverksette tiltak mot personell og andre relevante interessenter som har begått et brudd på informasjonssikkerhetspolicyen.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 41
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.5',
    category: 'people',
    name: 'Responsibilities after termination or change of employment',
    name_no: 'Ansvar etter opphør eller endring av ansettelse',
    description: 'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.',
    description_no: 'Informasjonssikkerhetsansvar og -plikter som forblir gyldige etter opphør eller endring av ansettelse, skal defineres, håndheves og kommuniseres til relevant personell og andre interessenter.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'assisted',
    sort_order: 42
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.6',
    category: 'people',
    name: 'Confidentiality or non-disclosure agreements',
    name_no: 'Taushetserklæringer',
    description: 'Confidentiality or non-disclosure agreements reflecting the organization\'s needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.',
    description_no: 'Taushetserklæringer eller konfidensialitetsavtaler som reflekterer organisasjonens behov for beskyttelse av informasjon, skal identifiseres, dokumenteres, regelmessig gjennomgås og signeres av personell og andre relevante interessenter.',
    priority: 'high',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 43
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.7',
    category: 'people',
    name: 'Remote working',
    name_no: 'Fjernarbeid',
    description: 'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization\'s premises.',
    description_no: 'Sikkerhetstiltak skal implementeres når personell arbeider eksternt for å beskytte informasjon som er tilgang til, behandlet eller lagret utenfor organisasjonens lokaler.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 44
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.6.8',
    category: 'people',
    name: 'Information security event reporting',
    name_no: 'Rapportering av sikkerhetshendelser',
    description: 'The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.',
    description_no: 'Organisasjonen skal sørge for en mekanisme for personell til å rapportere observerte eller mistenkte informasjonssikkerhetshendelser gjennom passende kanaler i tide.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 45
  },

  // A.7 Physical Controls (14 controls)
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.1',
    category: 'physical',
    name: 'Physical security perimeters',
    name_no: 'Fysiske sikkerhetsperimetere',
    description: 'Security perimeters shall be defined and used to protect areas that contain information and other associated assets.',
    description_no: 'Sikkerhetsperimetere skal defineres og brukes for å beskytte områder som inneholder informasjon og andre tilknyttede eiendeler.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 46
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.2',
    category: 'physical',
    name: 'Physical entry',
    name_no: 'Fysisk adgang',
    description: 'Secure areas shall be protected by appropriate entry controls and access points.',
    description_no: 'Sikre områder skal beskyttes av passende adgangskontroller og adgangspunkter.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'manual',
    sort_order: 47
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.3',
    category: 'physical',
    name: 'Securing offices, rooms and facilities',
    name_no: 'Sikring av kontorer, rom og fasiliteter',
    description: 'Physical security for offices, rooms and facilities shall be designed and implemented.',
    description_no: 'Fysisk sikkerhet for kontorer, rom og fasiliteter skal utformes og implementeres.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 48
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.4',
    category: 'physical',
    name: 'Physical security monitoring',
    name_no: 'Fysisk sikkerhetsovervåking',
    description: 'Premises shall be continuously monitored for unauthorized physical access.',
    description_no: 'Lokaler skal overvåkes kontinuerlig for uautorisert fysisk tilgang.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 49
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.5',
    category: 'physical',
    name: 'Protecting against physical and environmental threats',
    name_no: 'Beskyttelse mot fysiske og miljømessige trusler',
    description: 'Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.',
    description_no: 'Beskyttelse mot fysiske og miljømessige trusler, som naturkatastrofer og andre tilsiktede eller utilsiktede fysiske trusler mot infrastruktur, skal utformes og implementeres.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 50
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.6',
    category: 'physical',
    name: 'Working in secure areas',
    name_no: 'Arbeid i sikre områder',
    description: 'Security measures for working in secure areas shall be designed and implemented.',
    description_no: 'Sikkerhetstiltak for arbeid i sikre områder skal utformes og implementeres.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 51
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.7',
    category: 'physical',
    name: 'Clear desk and clear screen',
    name_no: 'Ryddig skrivebord og skjerm',
    description: 'Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.',
    description_no: 'Regler for ryddig skrivebord for papirer og flyttbare lagringsmedier og regler for tom skjerm for informasjonsbehandlingsfasiliteter skal defineres og håndheves på passende måte.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 52
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.8',
    category: 'physical',
    name: 'Equipment siting and protection',
    name_no: 'Plassering og beskyttelse av utstyr',
    description: 'Equipment shall be sited securely and protected.',
    description_no: 'Utstyr skal plasseres sikkert og beskyttes.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 53
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.9',
    category: 'physical',
    name: 'Security of assets off-premises',
    name_no: 'Sikkerhet for eiendeler utenfor lokaler',
    description: 'Off-site assets shall be protected.',
    description_no: 'Eiendeler utenfor lokaler skal beskyttes.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 54
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.10',
    category: 'physical',
    name: 'Storage media',
    name_no: 'Lagringsmedier',
    description: 'Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization\'s classification scheme and handling requirements.',
    description_no: 'Lagringsmedier skal administreres gjennom hele livssyklusen for anskaffelse, bruk, transport og avhending i samsvar med organisasjonens klassifiseringsskjema og håndteringskrav.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 55
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.11',
    category: 'physical',
    name: 'Supporting utilities',
    name_no: 'Støttefunksjoner',
    description: 'Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.',
    description_no: 'Informasjonsbehandlingsfasiliteter skal beskyttes mot strømbrudd og andre forstyrrelser forårsaket av feil i støttefunksjoner.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 56
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.12',
    category: 'physical',
    name: 'Cabling security',
    name_no: 'Kablingssikkerhet',
    description: 'Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.',
    description_no: 'Kabler som fører strøm, data eller støtter informasjonstjenester, skal beskyttes mot avlytting, interferens eller skade.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 57
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.13',
    category: 'physical',
    name: 'Equipment maintenance',
    name_no: 'Utstyrsvedlikehold',
    description: 'Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.',
    description_no: 'Utstyr skal vedlikeholdes korrekt for å sikre tilgjengelighet, integritet og konfidensialitet av informasjon.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 58
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.7.14',
    category: 'physical',
    name: 'Secure disposal or re-use of equipment',
    name_no: 'Sikker avhending eller gjenbruk av utstyr',
    description: 'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.',
    description_no: 'Utstyr som inneholder lagringsmedier, skal verifiseres for å sikre at eventuelle sensitive data og lisensiert programvare er fjernet eller sikkert overskrevet før avhending eller gjenbruk.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 59
  },

  // A.8 Technological Controls (34 controls)
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.1',
    category: 'technological',
    name: 'User endpoint devices',
    name_no: 'Brukerendepunktsenheter',
    description: 'Information stored on, processed by or accessible via user endpoint devices shall be protected.',
    description_no: 'Informasjon som er lagret på, behandlet av eller tilgjengelig via brukerendepunktsenheter, skal beskyttes.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 60
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.2',
    category: 'technological',
    name: 'Privileged access rights',
    name_no: 'Privilegerte tilgangsrettigheter',
    description: 'The allocation and use of privileged access rights shall be restricted and managed.',
    description_no: 'Tildeling og bruk av privilegerte tilgangsrettigheter skal begrenses og administreres.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 61
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.3',
    category: 'technological',
    name: 'Information access restriction',
    name_no: 'Begrensning av informasjonstilgang',
    description: 'Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.',
    description_no: 'Tilgang til informasjon og andre tilknyttede eiendeler skal begrenses i samsvar med den etablerte tematiske policyen for tilgangskontroll.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 62
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.4',
    category: 'technological',
    name: 'Access to source code',
    name_no: 'Tilgang til kildekode',
    description: 'Read and write access to source code, development tools and software libraries shall be appropriately managed.',
    description_no: 'Lese- og skrivetilgang til kildekode, utviklingsverktøy og programvarebiblioteker skal administreres på passende måte.',
    priority: 'high',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 63
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.5',
    category: 'technological',
    name: 'Secure authentication',
    name_no: 'Sikker autentisering',
    description: 'Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.',
    description_no: 'Sikker autentiseringsteknologier og -prosedyrer skal implementeres basert på informasjonstilgangsbegrensninger og den tematiske policyen for tilgangskontroll.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'identity_access',
    agent_capability: 'full',
    sort_order: 64
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.6',
    category: 'technological',
    name: 'Capacity management',
    name_no: 'Kapasitetsadministrasjon',
    description: 'The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.',
    description_no: 'Bruken av ressurser skal overvåkes og justeres i tråd med nåværende og forventede kapasitetskrav.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 65
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.7',
    category: 'technological',
    name: 'Protection against malware',
    name_no: 'Beskyttelse mot skadelig programvare',
    description: 'Protection against malware shall be implemented and supported by appropriate user awareness.',
    description_no: 'Beskyttelse mot skadelig programvare skal implementeres og støttes av passende brukerbevissthet.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 66
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.8',
    category: 'technological',
    name: 'Management of technical vulnerabilities',
    name_no: 'Håndtering av tekniske sårbarheter',
    description: 'Information about technical vulnerabilities of information systems in use shall be obtained, the organization\'s exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.',
    description_no: 'Informasjon om tekniske sårbarheter i informasjonssystemer i bruk skal innhentes, organisasjonens eksponering for slike sårbarheter skal evalueres, og passende tiltak skal iverksettes.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 67
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.9',
    category: 'technological',
    name: 'Configuration management',
    name_no: 'Konfigurasjonsstyring',
    description: 'Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.',
    description_no: 'Konfigurasjoner, inkludert sikkerhetskonfigurasjoner, av maskinvare, programvare, tjenester og nettverk skal etableres, dokumenteres, implementeres, overvåkes og gjennomgås.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 68
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.10',
    category: 'technological',
    name: 'Information deletion',
    name_no: 'Sletting av informasjon',
    description: 'Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.',
    description_no: 'Informasjon som er lagret i informasjonssystemer, enheter eller andre lagringsmedier, skal slettes når den ikke lenger er nødvendig.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 69
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.11',
    category: 'technological',
    name: 'Data masking',
    name_no: 'Datamaskering',
    description: 'Data masking shall be used in accordance with the organization\'s topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.',
    description_no: 'Datamaskering skal brukes i samsvar med organisasjonens tematiske policy for tilgangskontroll og andre relaterte tematiske policyer, og forretningskrav, med hensyn til gjeldende lovgivning.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 70
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.12',
    category: 'technological',
    name: 'Data leakage prevention',
    name_no: 'Forebygging av datalekkasje',
    description: 'Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.',
    description_no: 'Tiltak for forebygging av datalekkasje skal anvendes på systemer, nettverk og andre enheter som behandler, lagrer eller overfører sensitiv informasjon.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 71
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.13',
    category: 'technological',
    name: 'Information backup',
    name_no: 'Sikkerhetskopiering av informasjon',
    description: 'Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.',
    description_no: 'Sikkerhetskopier av informasjon, programvare og systemer skal vedlikeholdes og testes regelmessig i samsvar med den avtalte tematiske policyen for sikkerhetskopiering.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 72
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.14',
    category: 'technological',
    name: 'Redundancy of information processing facilities',
    name_no: 'Redundans av informasjonsbehandlingsfasiliteter',
    description: 'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.',
    description_no: 'Informasjonsbehandlingsfasiliteter skal implementeres med tilstrekkelig redundans for å oppfylle tilgjengelighetskrav.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 73
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.15',
    category: 'technological',
    name: 'Logging',
    name_no: 'Logging',
    description: 'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.',
    description_no: 'Logger som registrerer aktiviteter, unntak, feil og andre relevante hendelser, skal produseres, lagres, beskyttes og analyseres.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 74
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.16',
    category: 'technological',
    name: 'Monitoring activities',
    name_no: 'Overvåkingsaktiviteter',
    description: 'Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.',
    description_no: 'Nettverk, systemer og applikasjoner skal overvåkes for unormal atferd, og passende tiltak skal iverksettes for å evaluere potensielle informasjonssikkerhetshendelser.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 75
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.17',
    category: 'technological',
    name: 'Clock synchronization',
    name_no: 'Klokkesynkronisering',
    description: 'The clocks of information processing systems used by the organization shall be synchronized to approved time sources.',
    description_no: 'Klokkene til informasjonsbehandlingssystemer som brukes av organisasjonen, skal synkroniseres til godkjente tidskilder.',
    priority: 'low',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 76
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.18',
    category: 'technological',
    name: 'Use of privileged utility programs',
    name_no: 'Bruk av privilegerte verktøyprogrammer',
    description: 'The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.',
    description_no: 'Bruken av verktøyprogrammer som kan være i stand til å overstyre system- og applikasjonskontroller, skal begrenses og kontrolleres nøye.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 77
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.19',
    category: 'technological',
    name: 'Installation of software on operational systems',
    name_no: 'Installasjon av programvare på operasjonelle systemer',
    description: 'Procedures and measures shall be implemented to securely manage software installation on operational systems.',
    description_no: 'Prosedyrer og tiltak skal implementeres for å sikkert administrere programvareinstallasjon på operasjonelle systemer.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 78
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.20',
    category: 'technological',
    name: 'Networks security',
    name_no: 'Nettverkssikkerhet',
    description: 'Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.',
    description_no: 'Nettverk og nettverksenheter skal sikres, administreres og kontrolleres for å beskytte informasjon i systemer og applikasjoner.',
    priority: 'critical',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 79
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.21',
    category: 'technological',
    name: 'Security of network services',
    name_no: 'Sikkerhet for nettverkstjenester',
    description: 'Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.',
    description_no: 'Sikkerhetsmekanismer, tjenestenivåer og tjenestekrav for nettverkstjenester skal identifiseres, implementeres og overvåkes.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 80
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.22',
    category: 'technological',
    name: 'Segregation of networks',
    name_no: 'Nettverkssegmentering',
    description: 'Groups of information services, users and information systems shall be segregated in the organization\'s networks.',
    description_no: 'Grupper av informasjonstjenester, brukere og informasjonssystemer skal segregeres i organisasjonens nettverk.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 81
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.23',
    category: 'technological',
    name: 'Web filtering',
    name_no: 'Webfiltrering',
    description: 'Access to external websites shall be managed to reduce exposure to malicious content.',
    description_no: 'Tilgang til eksterne nettsteder skal administreres for å redusere eksponering for skadelig innhold.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 82
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.24',
    category: 'technological',
    name: 'Use of cryptography',
    name_no: 'Bruk av kryptografi',
    description: 'Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.',
    description_no: 'Regler for effektiv bruk av kryptografi, inkludert administrasjon av kryptografiske nøkler, skal defineres og implementeres.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 83
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.25',
    category: 'technological',
    name: 'Secure development life cycle',
    name_no: 'Sikker utviklingslivssyklus',
    description: 'Rules for the secure development of software and systems shall be established and applied.',
    description_no: 'Regler for sikker utvikling av programvare og systemer skal etableres og anvendes.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 84
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.26',
    category: 'technological',
    name: 'Application security requirements',
    name_no: 'Sikkerhetskrav for applikasjoner',
    description: 'Information security requirements shall be identified, specified and approved when developing or acquiring applications.',
    description_no: 'Informasjonssikkerhetskrav skal identifiseres, spesifiseres og godkjennes ved utvikling eller anskaffelse av applikasjoner.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 85
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.27',
    category: 'technological',
    name: 'Secure system architecture and engineering principles',
    name_no: 'Sikker systemarkitektur og ingeniørprinsipper',
    description: 'Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.',
    description_no: 'Prinsipper for ingeniørarbeid med sikre systemer skal etableres, dokumenteres, vedlikeholdes og anvendes på alle utviklingsaktiviteter for informasjonssystemer.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 86
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.28',
    category: 'technological',
    name: 'Secure coding',
    name_no: 'Sikker koding',
    description: 'Secure coding principles shall be applied to software development.',
    description_no: 'Sikre kodingsprinsipper skal anvendes på programvareutvikling.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 87
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.29',
    category: 'technological',
    name: 'Security testing in development and acceptance',
    name_no: 'Sikkerhetstesting i utvikling og akseptanse',
    description: 'Security testing processes shall be defined and implemented in the development life cycle.',
    description_no: 'Sikkerhetstestingsprosesser skal defineres og implementeres i utviklingslivssyklusen.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 88
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.30',
    category: 'technological',
    name: 'Outsourced development',
    name_no: 'Utkontraktert utvikling',
    description: 'The organization shall direct, monitor and review the activities related to outsourced system development.',
    description_no: 'Organisasjonen skal styre, overvåke og gjennomgå aktiviteter relatert til utkontraktert systemutvikling.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'assisted',
    sort_order: 89
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.31',
    category: 'technological',
    name: 'Separation of development, test and production environments',
    name_no: 'Separasjon av utviklings-, test- og produksjonsmiljøer',
    description: 'Development, testing and production environments shall be separated and secured.',
    description_no: 'Utviklings-, test- og produksjonsmiljøer skal separeres og sikres.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 90
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.32',
    category: 'technological',
    name: 'Change management',
    name_no: 'Endringsstyring',
    description: 'Changes to information processing facilities and information systems shall be subject to change management procedures.',
    description_no: 'Endringer i informasjonsbehandlingsfasiliteter og informasjonssystemer skal være underlagt prosedyrer for endringsstyring.',
    priority: 'high',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 91
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.33',
    category: 'technological',
    name: 'Test information',
    name_no: 'Testinformasjon',
    description: 'Test information shall be appropriately selected, protected and managed.',
    description_no: 'Testinformasjon skal velges, beskyttes og administreres på passende måte.',
    priority: 'medium',
    domain: 'security',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 92
  },
  {
    framework_id: 'iso27001',
    requirement_id: 'A.8.34',
    category: 'technological',
    name: 'Protection of information systems during audit testing',
    name_no: 'Beskyttelse av informasjonssystemer under revisjonstesting',
    description: 'Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.',
    description_no: 'Revisjonstester og andre forsikringsaktiviteter som involverer vurdering av operasjonelle systemer, skal planlegges og avtales mellom testeren og passende ledelse.',
    priority: 'low',
    domain: 'security',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 93
  }
];

// ============================================
// GDPR Requirements (12 Core Requirements)
// ============================================

export const GDPR_REQUIREMENTS: ComplianceRequirement[] = [
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art30',
    category: 'governance',
    name: 'Records of Processing Activities (ROPA)',
    name_no: 'Protokoll over behandlingsaktiviteter (ROPA)',
    description: 'Maintain records of all personal data processing activities including purposes, data categories, recipients, transfers, and retention periods.',
    description_no: 'Vedlikehold oversikt over alle behandlingsaktiviteter for personopplysninger, inkludert formål, datakategorier, mottakere, overføringer og oppbevaringsperioder.',
    priority: 'critical',
    domain: 'privacy',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 1
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art6',
    category: 'legal',
    name: 'Lawful Basis Documentation',
    name_no: 'Dokumentasjon av behandlingsgrunnlag',
    description: 'Document the lawful basis for each processing activity (consent, contract, legal obligation, vital interests, public task, legitimate interests).',
    description_no: 'Dokumenter det lovlige grunnlaget for hver behandlingsaktivitet (samtykke, kontrakt, rettslig forpliktelse, vitale interesser, offentlig oppgave, berettigede interesser).',
    priority: 'critical',
    domain: 'privacy',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 2
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art7',
    category: 'legal',
    name: 'Consent Management',
    name_no: 'Samtykkeadministrasjon',
    description: 'Implement mechanisms to obtain, record, and manage valid consent for data processing where consent is the lawful basis.',
    description_no: 'Implementer mekanismer for å innhente, registrere og administrere gyldig samtykke for databehandling der samtykke er det lovlige grunnlaget.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'operations',
    agent_capability: 'manual',
    sort_order: 3
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art15-22',
    category: 'governance',
    name: 'Data Subject Rights Procedures',
    name_no: 'Prosedyrer for registrertes rettigheter',
    description: 'Establish procedures to handle data subject rights requests: access, rectification, erasure, restriction, portability, and objection.',
    description_no: 'Etabler prosedyrer for å håndtere forespørsler om registrertes rettigheter: innsyn, retting, sletting, begrensning, dataportabilitet og innsigelse.',
    priority: 'critical',
    domain: 'privacy',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 4
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art44-49',
    category: 'legal',
    name: 'Transfer Impact Assessment (TIA)',
    name_no: 'Overføringskonsekvensvurdering (TIA)',
    description: 'Assess and document appropriate safeguards for international data transfers outside the EU/EEA.',
    description_no: 'Vurder og dokumenter passende sikkerhetstiltak for internasjonale dataoverføringer utenfor EU/EØS.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'full',
    sort_order: 5
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art35',
    category: 'governance',
    name: 'Data Protection Impact Assessment (DPIA)',
    name_no: 'Personvernkonsekvensvurdering (DPIA)',
    description: 'Conduct DPIAs for processing likely to result in high risk to individuals\' rights and freedoms.',
    description_no: 'Gjennomfør DPIA for behandling som sannsynligvis vil medføre høy risiko for enkeltpersoners rettigheter og friheter.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 6
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art13-14',
    category: 'legal',
    name: 'Privacy Policy & Transparency',
    name_no: 'Personvernerklæring og åpenhet',
    description: 'Provide clear, accessible privacy notices explaining how personal data is collected, used, and protected.',
    description_no: 'Gi klare, tilgjengelige personvernerklæringer som forklarer hvordan personopplysninger samles inn, brukes og beskyttes.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'governance',
    agent_capability: 'full',
    sort_order: 7
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art28',
    category: 'legal',
    name: 'Processor Agreements',
    name_no: 'Databehandleravtaler',
    description: 'Ensure data processing agreements are in place with all processors handling personal data on your behalf.',
    description_no: 'Sørg for at databehandleravtaler er på plass med alle databehandlere som behandler personopplysninger på dine vegne.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'supplier_ecosystem',
    agent_capability: 'assisted',
    sort_order: 8
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art33-34',
    category: 'governance',
    name: 'Data Breach Notification Procedures',
    name_no: 'Prosedyrer for varsling av databrudd',
    description: 'Establish procedures to detect, investigate, and report personal data breaches within 72 hours to supervisory authorities.',
    description_no: 'Etabler prosedyrer for å oppdage, undersøke og rapportere brudd på personopplysningssikkerheten innen 72 timer til tilsynsmyndigheter.',
    priority: 'critical',
    domain: 'privacy',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 9
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art37-39',
    category: 'governance',
    name: 'Data Protection Officer (DPO)',
    name_no: 'Personvernombud',
    description: 'Appoint a DPO if required, or document the decision not to appoint one with justification.',
    description_no: 'Utnevn et personvernombud hvis påkrevd, eller dokumenter beslutningen om å ikke utnevne et med begrunnelse.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'identity_access',
    agent_capability: 'manual',
    sort_order: 10
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art32',
    category: 'technological',
    name: 'Security of Processing',
    name_no: 'Sikkerhet ved behandling',
    description: 'Implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk.',
    description_no: 'Implementer passende tekniske og organisatoriske tiltak for å sikre et sikkerhetsnivå som er passende i forhold til risikoen.',
    priority: 'critical',
    domain: 'privacy',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 11
  },
  {
    framework_id: 'gdpr',
    requirement_id: 'GDPR-Art25',
    category: 'governance',
    name: 'Privacy by Design and Default',
    name_no: 'Innebygd personvern',
    description: 'Integrate data protection into processing activities and business practices from the design stage.',
    description_no: 'Integrer databeskyttelse i behandlingsaktiviteter og forretningspraksis fra designstadiet.',
    priority: 'high',
    domain: 'privacy',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 12
  }
];

// ============================================
// AI Act Requirements (8 Core Requirements)
// ============================================

export const AI_ACT_REQUIREMENTS: ComplianceRequirement[] = [
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art6',
    category: 'governance',
    name: 'AI System Risk Classification',
    name_no: 'Risikoklassifisering av AI-systemer',
    description: 'Classify all AI systems by risk level (unacceptable, high, limited, minimal) and document justification for each classification.',
    description_no: 'Klassifiser alle AI-systemer etter risikonivå (uakseptabel, høy, begrenset, minimal) og dokumenter begrunnelse for hver klassifisering.',
    priority: 'critical',
    domain: 'ai',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 1
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art11',
    category: 'governance',
    name: 'Technical Documentation',
    name_no: 'Teknisk dokumentasjon',
    description: 'Maintain comprehensive technical documentation for high-risk AI systems including design, development, and testing information.',
    description_no: 'Vedlikehold omfattende teknisk dokumentasjon for høyrisiko AI-systemer, inkludert informasjon om design, utvikling og testing.',
    priority: 'high',
    domain: 'ai',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 2
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art13',
    category: 'legal',
    name: 'Transparency Requirements',
    name_no: 'Åpenhetskrav',
    description: 'Ensure AI systems are designed to enable users to understand their operation and interpret outputs appropriately.',
    description_no: 'Sørg for at AI-systemer er utformet for å gjøre det mulig for brukere å forstå deres operasjon og tolke resultater på riktig måte.',
    priority: 'critical',
    domain: 'ai',
    sla_category: 'operations',
    agent_capability: 'full',
    sort_order: 3
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art14',
    category: 'governance',
    name: 'Human Oversight',
    name_no: 'Menneskelig tilsyn',
    description: 'Design high-risk AI systems to be effectively overseen by natural persons, including ability to intervene or stop operation.',
    description_no: 'Design høyrisiko AI-systemer slik at de effektivt kan overvåkes av fysiske personer, inkludert mulighet for å gripe inn eller stoppe operasjonen.',
    priority: 'critical',
    domain: 'ai',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 4
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art9',
    category: 'governance',
    name: 'Fundamental Rights Impact Assessment',
    name_no: 'Vurdering av grunnleggende rettigheter',
    description: 'Conduct assessments of high-risk AI systems\' impact on fundamental rights before deployment.',
    description_no: 'Gjennomfør vurderinger av høyrisiko AI-systemers innvirkning på grunnleggende rettigheter før implementering.',
    priority: 'high',
    domain: 'ai',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 5
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art71',
    category: 'governance',
    name: 'EU Database Registration',
    name_no: 'EU-databaseregistrering',
    description: 'Register high-risk AI systems in the EU database before placing on market or putting into service.',
    description_no: 'Registrer høyrisiko AI-systemer i EU-databasen før de markedsføres eller tas i bruk.',
    priority: 'high',
    domain: 'ai',
    sla_category: 'governance',
    agent_capability: 'assisted',
    sort_order: 6
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art43',
    category: 'governance',
    name: 'Conformity Assessment',
    name_no: 'Samsvarsvurdering',
    description: 'Complete conformity assessment procedures for high-risk AI systems before placing on market.',
    description_no: 'Fullfør samsvarsvurderingsprosedyrer for høyrisiko AI-systemer før de markedsføres.',
    priority: 'critical',
    domain: 'ai',
    sla_category: 'governance',
    agent_capability: 'manual',
    sort_order: 7
  },
  {
    framework_id: 'ai-act',
    requirement_id: 'AIACT-Art72',
    category: 'governance',
    name: 'Post-Market Monitoring',
    name_no: 'Overvåking etter markedsføring',
    description: 'Establish a post-market monitoring system to collect, document, and analyze data on AI system performance.',
    description_no: 'Etabler et system for overvåking etter markedsføring for å samle inn, dokumentere og analysere data om AI-systemets ytelse.',
    priority: 'high',
    domain: 'ai',
    sla_category: 'operations',
    agent_capability: 'assisted',
    sort_order: 8
  }
];

// ============================================
// Combined Export
// ============================================

export const ALL_COMPLIANCE_REQUIREMENTS: ComplianceRequirement[] = [
  ...ISO27001_CONTROLS,
  ...GDPR_REQUIREMENTS,
  ...AI_ACT_REQUIREMENTS
];

// Helper functions
export function getRequirementsByFramework(frameworkId: string): ComplianceRequirement[] {
  return ALL_COMPLIANCE_REQUIREMENTS.filter(r => r.framework_id === frameworkId);
}

export function getRequirementsByDomain(domain: RequirementDomain): ComplianceRequirement[] {
  return ALL_COMPLIANCE_REQUIREMENTS.filter(r => r.domain === domain);
}

export function getRequirementsByAgentCapability(capability: AgentCapability): ComplianceRequirement[] {
  return ALL_COMPLIANCE_REQUIREMENTS.filter(r => r.agent_capability === capability);
}

export function getCriticalRequirements(): ComplianceRequirement[] {
  return ALL_COMPLIANCE_REQUIREMENTS.filter(r => r.priority === 'critical');
}

export function getFrameworkStats(frameworkId: string) {
  const requirements = getRequirementsByFramework(frameworkId);
  return {
    total: requirements.length,
    byAgentCapability: {
      full: requirements.filter(r => r.agent_capability === 'full').length,
      assisted: requirements.filter(r => r.agent_capability === 'assisted').length,
      manual: requirements.filter(r => r.agent_capability === 'manual').length
    },
    byPriority: {
      critical: requirements.filter(r => r.priority === 'critical').length,
      high: requirements.filter(r => r.priority === 'high').length,
      medium: requirements.filter(r => r.priority === 'medium').length,
      low: requirements.filter(r => r.priority === 'low').length
    },
    byCategory: requirements.reduce((acc, r) => {
      acc[r.category] = (acc[r.category] || 0) + 1;
      return acc;
    }, {} as Record<string, number>)
  };
}
