import { supabase } from "@/integrations/supabase/client";

const demoDevices = [
  {
    name: "DESK-FIN-01",
    asset_type: "hardware",
    description: "Arbeidsstasjon – Økonomiavdelingen",
    risk_level: "low",
    criticality: "medium",
    lifecycle_status: "active",
    asset_manager: "Kari Nordmann",
    metadata: {
      is_demo_device: true,
      device_type: "workstation",
      os: "Windows 11 Pro",
      hostname: "DESK-FIN-01",
      status: "protected",
      encryption: "BitLocker",
      antivirus: "aktiv",
      mdm: "Intune",
      location: "Kontor – 2. etasje",
      backup: "OneDrive",
      last_patch_date: new Date(Date.now() - 5 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-FIN-001",
      llm_usage: [
        { name: "Copilot", provider: "Microsoft", accessLevel: "managed", sensitiveDataRisk: "low" },
      ],
    },
  },
  {
    name: "DESK-HR-02",
    asset_type: "hardware",
    description: "Arbeidsstasjon – HR-avdelingen",
    risk_level: "medium",
    criticality: "medium",
    lifecycle_status: "active",
    asset_manager: "Ole Hansen",
    metadata: {
      is_demo_device: true,
      device_type: "workstation",
      os: "Windows 11 Pro",
      hostname: "DESK-HR-02",
      status: "warning",
      encryption: "BitLocker",
      antivirus: "utgått",
      mdm: "Intune",
      location: "Kontor – 3. etasje",
      backup: "OneDrive",
      last_patch_date: new Date(Date.now() - 40 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-HR-002",
    },
  },
  {
    name: "LAPTOP-DEV-03",
    asset_type: "hardware",
    description: "Utvikler-laptop – Produktutvikling",
    risk_level: "low",
    criticality: "high",
    lifecycle_status: "active",
    asset_manager: "Lars Johansen",
    metadata: {
      is_demo_device: true,
      device_type: "workstation",
      os: "macOS Sonoma",
      hostname: "LAPTOP-DEV-03",
      status: "protected",
      encryption: "FileVault",
      antivirus: "aktiv",
      mdm: "Jamf",
      location: "Hybrid – hjemmekontor",
      backup: "Time Machine + iCloud",
      last_patch_date: new Date(Date.now() - 3 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-DEV-003",
      llm_usage: [
        { name: "ChatGPT", provider: "OpenAI", accessLevel: "unrestricted", sensitiveDataRisk: "high" },
        { name: "GitHub Copilot", provider: "Microsoft", accessLevel: "managed", sensitiveDataRisk: "medium" },
      ],
    },
  },
  {
    name: "LAPTOP-SALG-04",
    asset_type: "hardware",
    description: "Salgslaptop – uten sikkerhet",
    risk_level: "high",
    criticality: "medium",
    lifecycle_status: "active",
    asset_manager: null,
    metadata: {
      is_demo_device: true,
      device_type: "workstation",
      os: "Windows 11 Home",
      hostname: "LAPTOP-SALG-04",
      status: "critical",
      encryption: null,
      antivirus: null,
      mdm: null,
      location: null,
      backup: null,
      last_patch_date: null,
      serial_number: "SN-2024-SALG-004",
      nis2_mfa_enabled: false,
      nis2_assessment: {
        risk_analysis: { status: "not_assessed", notes: "", updatedAt: "", autoChecked: false },
        incident_handling: { status: "not_assessed", notes: "", updatedAt: "", autoChecked: false },
        business_continuity: { status: "fail", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
        encryption: { status: "fail", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
        access_control: { status: "fail", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
        mfa: { status: "fail", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
      },
      llm_usage: [
        { name: "ChatGPT", provider: "OpenAI", accessLevel: "unrestricted", sensitiveDataRisk: "high" },
        { name: "Gemini", provider: "Google", accessLevel: "unrestricted", sensitiveDataRisk: "high" },
      ],
    },
  },
  {
    name: "SRV-DC-01",
    asset_type: "hardware",
    description: "Domenecontroller – Serverrom A",
    risk_level: "medium",
    criticality: "critical",
    lifecycle_status: "active",
    asset_manager: "IT-drift",
    metadata: {
      is_demo_device: true,
      device_type: "server",
      os: "Windows Server 2022",
      hostname: "SRV-DC-01",
      status: "protected",
      encryption: "BitLocker",
      antivirus: "aktiv",
      mdm: null,
      location: "Serverrom A",
      backup: "daglig",
      last_patch_date: new Date(Date.now() - 12 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-SRV-001",
      nis2_mfa_enabled: true,
      nis2_assessment: {
        risk_analysis: { status: "pass", notes: "ROS-analyse gjennomført Q4 2025", updatedAt: "2025-12-15T10:00:00Z", autoChecked: false },
        incident_handling: { status: "pass", notes: "Hendelseshåndteringsplan godkjent", updatedAt: "2025-11-01T10:00:00Z", autoChecked: false },
        business_continuity: { status: "pass", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
        supply_chain: { status: "partial", notes: "Leverandørvurdering pågår", updatedAt: "2025-12-10T10:00:00Z", autoChecked: false },
        procurement_security: { status: "pass", notes: "", updatedAt: "2025-10-01T10:00:00Z", autoChecked: false },
        vulnerability_management: { status: "pass", notes: "", updatedAt: "2025-12-20T10:00:00Z", autoChecked: true },
        cyber_hygiene: { status: "partial", notes: "Opplæring planlagt Q1 2026", updatedAt: "2025-12-01T10:00:00Z", autoChecked: false },
        encryption: { status: "pass", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
        access_control: { status: "not_assessed", notes: "", updatedAt: "", autoChecked: false },
        mfa: { status: "pass", notes: "", updatedAt: "2025-12-01T10:00:00Z", autoChecked: true },
      },
    },
  },
  {
    name: "SRV-APP-02",
    asset_type: "hardware",
    description: "Applikasjonsserver – Azure VM",
    risk_level: "medium",
    criticality: "high",
    lifecycle_status: "active",
    asset_manager: "IT-drift",
    metadata: {
      is_demo_device: true,
      device_type: "server",
      os: "Ubuntu 24.04 LTS",
      hostname: "SRV-APP-02",
      status: "warning",
      encryption: "LUKS",
      antivirus: "ClamAV",
      mdm: null,
      location: "Azure – North Europe",
      backup: "ukentlig",
      last_patch_date: new Date(Date.now() - 45 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-SRV-002",
    },
  },
  {
    name: "MOB-CEO-01",
    asset_type: "hardware",
    description: "Mobiltelefon – Daglig leder",
    risk_level: "low",
    criticality: "high",
    lifecycle_status: "active",
    asset_manager: "Per Olsen",
    metadata: {
      is_demo_device: true,
      device_type: "mobile",
      os: "iOS 18",
      hostname: "MOB-CEO-01",
      status: "protected",
      encryption: "standard",
      antivirus: null,
      mdm: "Intune",
      location: "Mobil",
      backup: "iCloud",
      last_patch_date: new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-MOB-001",
      llm_usage: [
        { name: "ChatGPT", provider: "OpenAI", accessLevel: "unrestricted", sensitiveDataRisk: "high" },
      ],
    },
  },
  {
    name: "NAS-ARKIV-01",
    asset_type: "hardware",
    description: "Nettverkslagring – Arkiv",
    risk_level: "high",
    criticality: "high",
    lifecycle_status: "active",
    asset_manager: null,
    metadata: {
      is_demo_device: true,
      device_type: "nas",
      os: "Synology DSM 7.2",
      hostname: "NAS-ARKIV-01",
      status: "warning",
      encryption: null,
      antivirus: null,
      mdm: null,
      location: "Serverrom A",
      backup: "ukentlig",
      last_patch_date: new Date(Date.now() - 60 * 86400000).toISOString().slice(0, 10),
      serial_number: "SN-2024-NAS-001",
      raid_level: "RAID 5",
    },
  },
];

export async function seedDemoDevices(): Promise<number> {
  // Delete existing demo devices first
  await supabase.from("assets").delete().eq("asset_type", "hardware").filter("metadata->>is_demo_device", "eq", "true");

  const { data, error } = await supabase.from("assets").insert(demoDevices).select();
  if (error) throw error;
  return data?.length || 0;
}

export async function deleteDemoDevices(): Promise<number> {
  const { data, error } = await supabase
    .from("assets")
    .delete()
    .eq("asset_type", "hardware")
    .filter("metadata->>is_demo_device", "eq", "true")
    .select();
  if (error) throw error;
  return data?.length || 0;
}
