// Hardcoded demo vendors used as fallback when PDF analysis returns 0 suppliers
export const DEMO_VENDORS = [
  {
    name: "Microsoft 365",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II"],
    vendor: "Microsoft",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 18,
    compliance_score: 92,
    criticality: "high",
    url: "https://www.microsoft.com/microsoft-365",
  },
  {
    name: "Google Workspace",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II", "ISO 27017"],
    vendor: "Google",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 15,
    compliance_score: 95,
    criticality: "high",
    url: "https://workspace.google.com",
  },
  {
    name: "Salesforce",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II"],
    vendor: "Salesforce Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 22,
    compliance_score: 88,
    criticality: "high",
    url: "https://www.salesforce.com",
  },
  {
    name: "Slack",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["SOC 2 Type II"],
    vendor: "Salesforce Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 45,
    compliance_score: 62,
    criticality: "medium",
    url: "https://slack.com",
  },
  {
    name: "HubSpot",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["SOC 2 Type II"],
    vendor: "HubSpot Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 48,
    compliance_score: 58,
    criticality: "medium",
    url: "https://www.hubspot.com",
  },
  {
    name: "Amazon Web Services",
    type: "Cloud",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II", "ISO 27018"],
    vendor: "Amazon",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 12,
    compliance_score: 96,
    criticality: "high",
    url: "https://aws.amazon.com",
  },
  {
    name: "Dropbox Business",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["ISO 27001"],
    vendor: "Dropbox Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 52,
    compliance_score: 54,
    criticality: "low",
    url: "https://www.dropbox.com/business",
  },
  {
    name: "Visma",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001"],
    vendor: "Visma AS",
    country: "Norge",
    region: "Europa",
    risk_level: "low",
    risk_score: 10,
    compliance_score: 90,
    criticality: "high",
    url: "https://www.visma.no",
  },
  {
    name: "Tripletex",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001"],
    vendor: "Tripletex AS",
    country: "Norge",
    region: "Europa",
    risk_level: "low",
    risk_score: 14,
    compliance_score: 88,
    criticality: "high",
    url: "https://www.tripletex.no",
  },
  {
    name: "Zendesk",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["SOC 2 Type II", "ISO 27001"],
    vendor: "Zendesk Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 20,
    compliance_score: 85,
    criticality: "medium",
    url: "https://www.zendesk.com",
  },
  {
    name: "Jira Cloud",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II"],
    vendor: "Atlassian",
    country: "Australia",
    region: "Asia-Stillehavet",
    risk_level: "low",
    risk_score: 19,
    compliance_score: 87,
    criticality: "high",
    url: "https://www.atlassian.com/software/jira",
  },
  {
    name: "Docusign",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II"],
    vendor: "DocuSign Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 16,
    compliance_score: 91,
    criticality: "medium",
    url: "https://www.docusign.com",
  },
  {
    name: "Notion",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["SOC 2 Type II"],
    vendor: "Notion Labs Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 42,
    compliance_score: 64,
    criticality: "medium",
    url: "https://www.notion.so",
  },
  {
    name: "Snowflake",
    type: "Cloud",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II", "ISO 27018"],
    vendor: "Snowflake Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 13,
    compliance_score: 94,
    criticality: "high",
    url: "https://www.snowflake.com",
  },
  {
    name: "Stripe",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["PCI DSS", "SOC 2 Type II", "ISO 27001"],
    vendor: "Stripe Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 11,
    compliance_score: 97,
    criticality: "high",
    url: "https://stripe.com",
  },
  {
    name: "Mailchimp",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["SOC 2 Type II"],
    vendor: "Intuit Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 50,
    compliance_score: 56,
    criticality: "low",
    url: "https://mailchimp.com",
  },
  {
    name: "Superoffice",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001"],
    vendor: "SuperOffice AS",
    country: "Norge",
    region: "Europa",
    risk_level: "low",
    risk_score: 12,
    compliance_score: 89,
    criticality: "medium",
    url: "https://www.superoffice.no",
  },
  {
    name: "Zoom",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["SOC 2 Type II", "ISO 27001"],
    vendor: "Zoom Video Communications",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 24,
    compliance_score: 82,
    criticality: "medium",
    url: "https://zoom.us",
  },
];
