// Hardcoded demo vendors used as fallback when PDF analysis returns 0 suppliers
export const DEMO_VENDORS = [
  {
    name: "Microsoft 365",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II"],
    vendor: "Microsoft",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 18,
    compliance_score: 92,
    criticality: "high",
    url: "https://www.microsoft.com/microsoft-365",
  },
  {
    name: "Google Workspace",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II", "ISO 27017"],
    vendor: "Google",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 15,
    compliance_score: 95,
    criticality: "high",
    url: "https://workspace.google.com",
  },
  {
    name: "Salesforce",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II"],
    vendor: "Salesforce Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 22,
    compliance_score: 88,
    criticality: "high",
    url: "https://www.salesforce.com",
  },
  {
    name: "Slack",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["SOC 2 Type II"],
    vendor: "Salesforce Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 45,
    compliance_score: 62,
    criticality: "medium",
    url: "https://slack.com",
  },
  {
    name: "HubSpot",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["SOC 2 Type II"],
    vendor: "HubSpot Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 48,
    compliance_score: 58,
    criticality: "medium",
    url: "https://www.hubspot.com",
  },
  {
    name: "Amazon Web Services",
    type: "Cloud",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001", "SOC 2 Type II", "ISO 27018"],
    vendor: "Amazon",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "low",
    risk_score: 12,
    compliance_score: 96,
    criticality: "high",
    url: "https://aws.amazon.com",
  },
  {
    name: "Dropbox Business",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: false,
    certifications: ["ISO 27001"],
    vendor: "Dropbox Inc.",
    country: "USA",
    region: "Nord-Amerika",
    risk_level: "medium",
    risk_score: 52,
    compliance_score: 54,
    criticality: "low",
    url: "https://www.dropbox.com/business",
  },
  {
    name: "Visma",
    type: "SaaS",
    dataProcessing: true,
    hasDPA: true,
    certifications: ["ISO 27001"],
    vendor: "Visma AS",
    country: "Norge",
    region: "Europa",
    risk_level: "low",
    risk_score: 10,
    compliance_score: 90,
    criticality: "high",
    url: "https://www.visma.no",
  },
];
