// Framework-agnostic gap-analysis questionnaire registry.
// GDPR uses the curated MATURITY_AREAS set; all other frameworks fall back to
// an auto-generated questionnaire derived from getRequirementsByFramework().

import { MATURITY_AREAS } from "./trustMaturityQuestions";
import {
  getRequirementsByFramework,
  type ComplianceRequirement,
} from "./complianceRequirementsData";

export type GapAnswer = "yes" | "no" | "partial" | "unsure" | "n_a";

export interface GapQuestion {
  id: string;
  text: string;
  reference?: string;
  /** Optional follow-up service / activity suggestion key. */
  suggestedAction?: string;
}

export interface GapSection {
  id: string;
  title: string;
  subtitle?: string;
  questions: GapQuestion[];
}

export interface FrameworkQuestionnaireDefinition {
  frameworkId: string;
  title: string;
  intro: string;
  sections: GapSection[];
  totalQuestions: number;
  /** True when this is an auto-generated fallback rather than a curated set. */
  autoGenerated: boolean;
}

// ---- GDPR (curated) ---------------------------------------------------------

const GDPR_SUGGESTED: Record<string, string> = {
  "gov.dpo": "Utpek personvernkontakt eller engasjer ekstern DPO.",
  "gov.privacy_policy": "Publiser personvernerklæring på nettsiden.",
  "gov.internal_policy": "Lag intern personvernpolicy og distribuer til ansatte.",
  "gov.records": "Opprett behandlingsprotokoll (Art. 30).",
  "gov.training": "Etabler årlig personvernopplæring.",
  "ops.encryption": "Aktiver kryptering i hvile og overføring.",
  "ia.mfa": "Påkrev tofaktor for systemer med personopplysninger.",
  "ops.breach": "Etabler rutine for 72-timers brudd-varsling.",
  "ops.logging": "Aktiver tilgangslogging og overvåking.",
  "ops.backup": "Sett opp regelmessig backup og test gjenoppretting.",
  "pri.legal_basis": "Kartlegg lovlig grunnlag for alle behandlinger.",
  "pri.minimization": "Gjennomgå datafelter og fjern unødvendige.",
  "pri.retention": "Definer oppbevaringsperioder og automatisk sletting.",
  "pri.rights": "Etabler rutine for innsyn, retting og sletting.",
  "pri.transfer": "Sikre gyldig overføringsgrunnlag (SCC/adequacy).",
  "tp.inventory": "Opprett oversikt over alle databehandlere.",
  "tp.dpa": "Signer DPA med alle databehandlere.",
  "tp.risk_assessment": "Innfør risikovurdering før nye leverandører.",
  "tp.subprocessor_notice": "Be om varslingsavtale ved subprosessor-endringer.",
};

function buildGdprDefinition(): FrameworkQuestionnaireDefinition {
  const sections: GapSection[] = MATURITY_AREAS.map((area) => ({
    id: area.id,
    title: area.title,
    subtitle: area.subtitle,
    questions: area.questions.map((q) => ({
      id: q.id,
      text: q.text,
      reference: q.article,
      suggestedAction: GDPR_SUGGESTED[q.id],
    })),
  }));
  return {
    frameworkId: "gdpr",
    title: "GDPR – Gap-analyse",
    intro:
      "Svar på spørsmålene under for å identifisere gap mot GDPR. Du kan lagre og fortsette senere.",
    sections,
    totalQuestions: sections.reduce((n, s) => n + s.questions.length, 0),
    autoGenerated: false,
  };
}

// ---- Auto-generated fallback for any other framework ------------------------

function questionFromRequirement(req: ComplianceRequirement): GapQuestion {
  return {
    id: req.requirement_id,
    text: `Er kravet "${req.name_no}" oppfylt i virksomheten?`,
    reference: req.requirement_id,
    suggestedAction: req.description_no,
  };
}

function buildAutoDefinition(frameworkId: string): FrameworkQuestionnaireDefinition {
  const requirements = getRequirementsByFramework(frameworkId);
  const byCategory = new Map<string, ComplianceRequirement[]>();
  for (const r of requirements) {
    const key = r.category || "other";
    if (!byCategory.has(key)) byCategory.set(key, []);
    byCategory.get(key)!.push(r);
  }
  const sections: GapSection[] = Array.from(byCategory.entries()).map(([cat, items]) => ({
    id: cat,
    title: cat.charAt(0).toUpperCase() + cat.slice(1),
    questions: items
      .sort((a, b) => a.sort_order - b.sort_order)
      .map(questionFromRequirement),
  }));
  return {
    frameworkId,
    title: "Gap-analyse",
    intro:
      "Auto-generert spørreskjema basert på krav i regelverket. Svar for å identifisere gap.",
    sections,
    totalQuestions: sections.reduce((n, s) => n + s.questions.length, 0),
    autoGenerated: true,
  };
}

const CURATED: Record<string, () => FrameworkQuestionnaireDefinition> = {
  gdpr: buildGdprDefinition,
};

export function getFrameworkQuestionnaire(
  frameworkId: string,
): FrameworkQuestionnaireDefinition | null {
  if (CURATED[frameworkId]) return CURATED[frameworkId]();
  const auto = buildAutoDefinition(frameworkId);
  if (auto.totalQuestions === 0) return null;
  return auto;
}

// ---- Scoring ---------------------------------------------------------------

export interface SectionScore {
  id: string;
  title: string;
  total: number;
  yes: number;
  partial: number;
  no: number;
  unsure: number;
  na: number;
  /** 0-100 weighted score (yes=1, partial=0.5, n/a excluded). */
  score: number;
}

export interface QuestionnaireScore {
  total: number;
  answered: number;
  yes: number;
  partial: number;
  no: number;
  unsure: number;
  na: number;
  /** 0-100 weighted score. */
  score: number;
  /** 0-4 maturity level derived from score. */
  maturityLevel: number;
  sections: SectionScore[];
  /** Gap items (no + partial), ordered by section. */
  gaps: Array<{ sectionId: string; sectionTitle: string; question: GapQuestion; answer: GapAnswer }>;
}

export function scoreQuestionnaire(
  def: FrameworkQuestionnaireDefinition,
  answers: Record<string, GapAnswer>,
): QuestionnaireScore {
  const sections: SectionScore[] = [];
  const gaps: QuestionnaireScore["gaps"] = [];
  let yes = 0, partial = 0, no = 0, unsure = 0, na = 0, answered = 0;

  for (const s of def.sections) {
    let sYes = 0, sPartial = 0, sNo = 0, sUnsure = 0, sNa = 0;
    for (const q of s.questions) {
      const a = answers[q.id];
      if (!a) continue;
      answered++;
      if (a === "yes") { sYes++; yes++; }
      else if (a === "partial") {
        sPartial++; partial++;
        gaps.push({ sectionId: s.id, sectionTitle: s.title, question: q, answer: a });
      }
      else if (a === "no") {
        sNo++; no++;
        gaps.push({ sectionId: s.id, sectionTitle: s.title, question: q, answer: a });
      }
      else if (a === "unsure") { sUnsure++; unsure++; }
      else if (a === "n_a") { sNa++; na++; }
    }
    const denom = s.questions.length - sNa;
    const score = denom > 0 ? Math.round(((sYes + sPartial * 0.5) / denom) * 100) : 0;
    sections.push({
      id: s.id,
      title: s.title,
      total: s.questions.length,
      yes: sYes, partial: sPartial, no: sNo, unsure: sUnsure, na: sNa,
      score,
    });
  }

  const denom = def.totalQuestions - na;
  const score = denom > 0 ? Math.round(((yes + partial * 0.5) / denom) * 100) : 0;
  // 0-4 maturity mapping: 0-19 = 0, 20-39 = 1, 40-59 = 2, 60-79 = 3, 80-100 = 4
  const maturityLevel = Math.min(4, Math.floor(score / 20));

  return {
    total: def.totalQuestions,
    answered, yes, partial, no, unsure, na,
    score, maturityLevel, sections, gaps,
  };
}
