// Definition of the Trust Center "content matrix" — the structured single-source
// view of every field that can appear in a Trust Profile (one-pager) and a
// Trust Center (full view). Mirrors the editorial spec from the screenshots.

export type FieldVisibility = "profile" | "center" | "hidden";

export interface MatrixRow {
  id: string;
  labelNb: string;
  labelEn: string;
  helpNb?: string;
  helpEn?: string;
  /** Short human description of how this field shows up on the one-pager. */
  profileNb: string;
  profileEn: string;
  profileVisibility: FieldVisibility;
  /** Short human description of how this field shows up in the full Trust Center. */
  centerNb: string;
  centerEn: string;
  centerVisibility: FieldVisibility;
  /** Where to take the user when they click "Edit". */
  editTarget?:
    | { kind: "section"; anchor: string }
    | { kind: "navigate"; href: string };
}

export interface MatrixGroup {
  id: string;
  labelNb: string;
  labelEn: string;
  rows: MatrixRow[];
}

export const TRUST_CONTENT_MATRIX: MatrixGroup[] = [
  {
    id: "identity",
    labelNb: "Identitet og organisasjon",
    labelEn: "Identity & organisation",
    rows: [
      {
        id: "company_name_logo",
        labelNb: "Selskapsnavn og logo",
        labelEn: "Company name & logo",
        helpNb: "Bedriftsnavn og visuell identitet",
        helpEn: "Company name and visual identity",
        profileNb: "Vises i header",
        profileEn: "Shown in header",
        profileVisibility: "profile",
        centerNb: "Vises i header",
        centerEn: "Shown in header",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#company" },
      },
      {
        id: "short_description",
        labelNb: "Kort selskapsbeskrivelse",
        labelEn: "Short company description",
        helpNb: "Hva selskapet gjør",
        helpEn: "What the company does",
        profileNb: "2–3 setninger under tittel",
        profileEn: "2–3 sentences under title",
        profileVisibility: "profile",
        centerNb: "Full beskrivelse",
        centerEn: "Full description",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#company" },
      },
      {
        id: "org_metadata",
        labelNb: "Org.nr, land, nettside, bransje",
        labelEn: "Org no., country, website, industry",
        helpNb: "Identifiserende metadata",
        helpEn: "Identifying metadata",
        profileNb: "Vises i meta-rad",
        profileEn: "Shown in meta row",
        profileVisibility: "profile",
        centerNb: "Samme + kategori, antall ansatte, hovedkontor",
        centerEn: "Same + category, employees, HQ",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#company" },
      },
      {
        id: "contact_info",
        labelNb: "Kontaktinformasjon",
        labelEn: "Contact information",
        helpNb: "Generell, personvern, sikkerhet, post",
        helpEn: "General, privacy, security, postal",
        profileNb: "Rolleadresser uten personnavn",
        profileEn: "Role addresses without person names",
        profileVisibility: "profile",
        centerNb: "Samme + utvidede kontakter (hendelse, juridisk)",
        centerEn: "Same + extended contacts (incident, legal)",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#company" },
      },
      {
        id: "additional_notes",
        labelNb: "Tilleggsnotater",
        labelEn: "Additional notes",
        helpNb: "Fritekst om sletterutiner, datalagring",
        helpEn: "Free text about deletion routines, data storage",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full fritekst tilgjengelig",
        centerEn: "Full free text available",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#company" },
      },
    ],
  },
  {
    id: "score",
    labelNb: "Score og modenhet",
    labelEn: "Score & maturity",
    rows: [
      {
        id: "trust_score",
        labelNb: "Trust Score",
        labelEn: "Trust Score",
        helpNb: "Aggregert tall 0–100",
        helpEn: "Aggregated 0–100",
        profileNb: "Aggregert score med tillitsnivå",
        profileEn: "Aggregated score with trust level",
        profileVisibility: "profile",
        centerNb: "Samme + forklaring av vekting og beregning",
        centerEn: "Same + explanation of weighting and calculation",
        centerVisibility: "center",
      },
      {
        id: "maturity_per_area",
        labelNb: "Modenhet per kontrollområde",
        labelEn: "Maturity per control area",
        helpNb: "Governance, Security, Privacy, Third-Party",
        helpEn: "Governance, Security, Privacy, Third-Party",
        profileNb: "4 prosent-barer med fargekoding",
        profileEn: "4 percent bars with colour coding",
        profileVisibility: "profile",
        centerNb: "Samme + drilldown per kontrollpunkt med oppfylt/mangler-status",
        centerEn: "Same + drilldown per control with fulfilled/missing status",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#security" },
      },
      {
        id: "detailed_controls",
        labelNb: "Detaljerte kontroller",
        labelEn: "Detailed controls",
        helpNb: "Eks: 13/17 oppfylt, hva mangler hva er på plass",
        helpEn: "Eg: 13/17 fulfilled, what's missing, what's in place",
        profileNb: "Ikke synlig per kontroll",
        profileEn: "Not visible per control",
        profileVisibility: "hidden",
        centerNb: "Full liste med status og handlingsforslag",
        centerEn: "Full list with status and recommendations",
        centerVisibility: "center",
        editTarget: { kind: "section", anchor: "#security" },
      },
    ],
  },
  {
    id: "regulations",
    labelNb: "Regelverk og rammeverk",
    labelEn: "Regulations & frameworks",
    rows: [
      {
        id: "active_frameworks",
        labelNb: "Aktiverte regelverk",
        labelEn: "Active frameworks",
        helpNb: "GDPR, NIS2, DORA, AI Act, ISO 27001",
        helpEn: "GDPR, NIS2, DORA, AI Act, ISO 27001",
        profileNb: "Antall + navnliste i sammendragsboks",
        profileEn: "Count + name list in summary",
        profileVisibility: "profile",
        centerNb: "Per regelverk: dekningsgrad, kontroller, evidens",
        centerEn: "Per framework: coverage, controls, evidence",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/regulations" },
      },
      {
        id: "certifications",
        labelNb: "Sertifiseringer",
        labelEn: "Certifications",
        helpNb: "ISO 27001, SOC 2 osv.",
        helpEn: "ISO 27001, SOC 2 etc.",
        profileNb: "Antall + status (eks. \"ISO 27001 påbegynt\")",
        profileEn: "Count + status (eg. \"ISO 27001 in progress\")",
        profileVisibility: "profile",
        centerNb: "Per sertifisering: scope, sertifiseringsorgan, gyldighet",
        centerEn: "Per certification: scope, body, validity",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/evidence" },
      },
      {
        id: "dpa_status",
        labelNb: "DPA-status",
        labelEn: "DPA status",
        helpNb: "Standard databehandleravtale",
        helpEn: "Standard data processing agreement",
        profileNb: "Tilgjengelig (ja/nei)",
        profileEn: "Available (yes/no)",
        profileVisibility: "profile",
        centerNb: "Lesbar DPA + signeringsprosess",
        centerEn: "Readable DPA + signing process",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/evidence" },
      },
    ],
  },
  {
    id: "privacy",
    labelNb: "Personvern og datahåndtering",
    labelEn: "Privacy & data handling",
    rows: [
      {
        id: "gdpr_status",
        labelNb: "GDPR-status",
        labelEn: "GDPR status",
        helpNb: "Compliance-vurdering",
        helpEn: "Compliance assessment",
        profileNb: "Inngår i Privacy & Data Handling-prosent",
        profileEn: "Included in Privacy & Data Handling percent",
        profileVisibility: "profile",
        centerNb: "Full vurdering med begrunnelse",
        centerEn: "Full assessment with justification",
        centerVisibility: "center",
      },
      {
        id: "data_types",
        labelNb: "Datatyper som behandles",
        labelEn: "Data types processed",
        helpNb: "Navn, e-post, IP-adresse osv. (typisk 10–15 typer)",
        helpEn: "Name, email, IP address etc. (typically 10–15 types)",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full liste med beskrivelse per type",
        centerEn: "Full list with description per type",
        centerVisibility: "center",
      },
      {
        id: "storage_locations",
        labelNb: "Datalagringslokasjoner",
        labelEn: "Data storage locations",
        helpNb: "Land og region for lagring",
        helpEn: "Country and region for storage",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Per lokasjon: tjenester, formål, leverandør",
        centerEn: "Per location: services, purpose, vendor",
        centerVisibility: "center",
      },
      {
        id: "transfer_mechanisms",
        labelNb: "Overføringsmekanismer",
        labelEn: "Transfer mechanisms",
        helpNb: "SCC, EU adequacy decision osv.",
        helpEn: "SCC, EU adequacy decision etc.",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full liste med rettsgrunnlag",
        centerEn: "Full list with legal basis",
        centerVisibility: "center",
      },
      {
        id: "retention_policy",
        labelNb: "Oppbevaringspolicy",
        labelEn: "Retention policy",
        helpNb: "Hvor lenge data lagres",
        helpEn: "How long data is stored",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Detaljert per datatype og formål",
        centerEn: "Detailed per data type and purpose",
        centerVisibility: "center",
      },
      {
        id: "gdpr_legal_basis",
        labelNb: "GDPR-rettsgrunnlag",
        labelEn: "GDPR legal basis",
        helpNb: "Art. 6, 9, 10",
        helpEn: "Art. 6, 9, 10",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Per behandling med begrunnelse",
        centerEn: "Per processing with justification",
        centerVisibility: "center",
      },
      {
        id: "privacy_policy_doc",
        labelNb: "Personvernerklæring",
        labelEn: "Privacy policy",
        helpNb: "Selskapets policy-dokument",
        helpEn: "Company policy document",
        profileNb: "Ikke duplisert her",
        profileEn: "Not duplicated here",
        profileVisibility: "hidden",
        centerNb: "Lesbar i full versjon",
        centerEn: "Readable in full version",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/policies" },
      },
    ],
  },
  {
    id: "security",
    labelNb: "Sikkerhet",
    labelEn: "Security",
    rows: [
      {
        id: "security_maturity",
        labelNb: "Sikkerhetsmodenhet",
        labelEn: "Security maturity",
        helpNb: "Aggregert score",
        helpEn: "Aggregated score",
        profileNb: "Inngår i Security-prosent",
        profileEn: "Included in Security percent",
        profileVisibility: "profile",
        centerNb: "Detaljert vurdering per dimensjon",
        centerEn: "Detailed assessment per dimension",
        centerVisibility: "center",
      },
      {
        id: "encryption",
        labelNb: "Kryptering",
        labelEn: "Encryption",
        helpNb: "AES-256, TLS osv.",
        helpEn: "AES-256, TLS etc.",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Standarder, scope og implementasjonsdetaljer",
        centerEn: "Standards, scope and implementation details",
        centerVisibility: "center",
      },
      {
        id: "access_control",
        labelNb: "Tilgangskontroll",
        labelEn: "Access control",
        helpNb: "RBAC, MFA, Least privilege",
        helpEn: "RBAC, MFA, Least privilege",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full beskrivelse av tiltak",
        centerEn: "Full description of measures",
        centerVisibility: "center",
      },
      {
        id: "pentest",
        labelNb: "Penetrasjonstesting og bug bounty",
        labelEn: "Penetration testing & bug bounty",
        helpNb: "Test-frekvens og programmer",
        helpEn: "Test frequency and programmes",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Resultater og oppfølging",
        centerEn: "Results and follow-up",
        centerVisibility: "center",
      },
      {
        id: "security_training",
        labelNb: "Sikkerhetsopplæring",
        labelEn: "Security training",
        helpNb: "Ansattes opplæring",
        helpEn: "Employee training",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Program, frekvens og dekning",
        centerEn: "Programme, frequency and coverage",
        centerVisibility: "center",
      },
    ],
  },
  {
    id: "incidents",
    labelNb: "Hendelser og kontinuitet",
    labelEn: "Incidents & continuity",
    rows: [
      {
        id: "incident_handling",
        labelNb: "Hendelseshåndtering",
        labelEn: "Incident handling",
        helpNb: "Prosedyrer for sikkerhetsbrudd",
        helpEn: "Procedures for security breaches",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full beskrivelse + varslingsrutiner",
        centerEn: "Full description + notification routines",
        centerVisibility: "center",
      },
      {
        id: "business_continuity",
        labelNb: "Forretningskontinuitet",
        labelEn: "Business continuity",
        helpNb: "Backup, recovery, oppetid",
        helpEn: "Backup, recovery, uptime",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "SLA, RTO, RPO og kontinuitetsplaner",
        centerEn: "SLA, RTO, RPO and continuity plans",
        centerVisibility: "center",
      },
    ],
  },
  {
    id: "ai_supply",
    labelNb: "AI og leverandørstyring",
    labelEn: "AI & vendor management",
    rows: [
      {
        id: "third_party_maturity",
        labelNb: "Tredjepart og supply chain-modenhet",
        labelEn: "Third-party & supply chain maturity",
        helpNb: "Aggregert score",
        helpEn: "Aggregated score",
        profileNb: "Inngår i Third-Party-prosent",
        profileEn: "Included in Third-Party percent",
        profileVisibility: "profile",
        centerNb: "Detaljert vurdering per dimensjon",
        centerEn: "Detailed assessment per dimension",
        centerVisibility: "center",
      },
      {
        id: "ai_use",
        labelNb: "AI-bruk",
        labelEn: "AI use",
        helpNb: "Hvilke AI-systemer brukes og hvordan",
        helpEn: "Which AI systems are used and how",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full beskrivelse av AI-bruk og governance",
        centerEn: "Full description of AI use and governance",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/ai-systems" },
      },
      {
        id: "vendor_risk_mgmt",
        labelNb: "Leverandørrisikostyring",
        labelEn: "Vendor risk management",
        helpNb: "Hvordan tredjeparter vurderes",
        helpEn: "How third parties are assessed",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Prosess og kriterier",
        centerEn: "Process and criteria",
        centerVisibility: "center",
      },
      {
        id: "subprocessors",
        labelNb: "Underleverandører",
        labelEn: "Sub-processors",
        helpNb: "Liste med rolle og formål",
        helpEn: "List with role and purpose",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full liste: navn, rolle, datatilgang, lokasjon",
        centerEn: "Full list: name, role, data access, location",
        centerVisibility: "center",
      },
    ],
  },
  {
    id: "documents",
    labelNb: "Dokumenter og policyer",
    labelEn: "Documents & policies",
    rows: [
      {
        id: "doc_privacy_policy",
        labelNb: "Personvernerklæring",
        labelEn: "Privacy policy",
        helpNb: "Selskapets policy",
        helpEn: "Company policy",
        profileNb: "Ikke duplisert her",
        profileEn: "Not duplicated here",
        profileVisibility: "hidden",
        centerNb: "Lesbar struktur",
        centerEn: "Readable structure",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/policies" },
      },
      {
        id: "doc_security_policy",
        labelNb: "Sikkerhetsretningslinjer",
        labelEn: "Security policy",
        helpNb: "Intern policy",
        helpEn: "Internal policy",
        profileNb: "Ikke duplisert her",
        profileEn: "Not duplicated here",
        profileVisibility: "hidden",
        centerNb: "Lesbar struktur",
        centerEn: "Readable structure",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/policies" },
      },
      {
        id: "doc_dpa",
        labelNb: "Standard databehandleravtale",
        labelEn: "Standard DPA",
        helpNb: "DPA",
        helpEn: "DPA",
        profileNb: "Status i sammendragsboks",
        profileEn: "Status in summary box",
        profileVisibility: "profile",
        centerNb: "Lesbar full DPA",
        centerEn: "Readable full DPA",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/evidence" },
      },
      {
        id: "doc_risk_assessment",
        labelNb: "Risikovurdering",
        labelEn: "Risk assessment",
        helpNb: "Årlig vurdering",
        helpEn: "Annual assessment",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Lesbar full vurdering",
        centerEn: "Readable full assessment",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/evidence" },
      },
      {
        id: "doc_other",
        labelNb: "Andre dokumenter",
        labelEn: "Other documents",
        helpNb: "Sertifikater, rapporter osv.",
        helpEn: "Certificates, reports etc.",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Komplett bibliotek",
        centerEn: "Complete library",
        centerVisibility: "center",
        editTarget: { kind: "navigate", href: "/trust-center/evidence" },
      },
    ],
  },
  {
    id: "signature",
    labelNb: "Signatur og verifikasjon",
    labelEn: "Signature & verification",
    rows: [
      {
        id: "signature_status",
        labelNb: "Signatur-status",
        labelEn: "Signature status",
        helpNb: "Kryptografisk verifikasjon",
        helpEn: "Cryptographic verification",
        profileNb: "\"Kryptografisk verifiserbar\" + dato + se bevis",
        profileEn: "\"Cryptographically verifiable\" + date + see evidence",
        profileVisibility: "profile",
        centerNb: "Samme — én signatur dekker alt",
        centerEn: "Same — one signature covers everything",
        centerVisibility: "center",
      },
      {
        id: "verify_page",
        labelNb: "Verifikasjonsside",
        labelEn: "Verification page",
        helpNb: "trust.mynder.no/.../verify",
        helpEn: "trust.mynder.no/.../verify",
        profileNb: "Lenke fra header",
        profileEn: "Link from header",
        profileVisibility: "profile",
        centerNb: "Samme lenke",
        centerEn: "Same link",
        centerVisibility: "center",
      },
      {
        id: "manifest_hash",
        labelNb: "Manifest-hash",
        labelEn: "Manifest hash",
        helpNb: "Tekniske detaljer",
        helpEn: "Technical details",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Tilgjengelig på verifikasjonsside",
        centerEn: "Available on verification page",
        centerVisibility: "center",
      },
      {
        id: "activity_log",
        labelNb: "Aktivitetslogg",
        labelEn: "Activity log",
        helpNb: "Hvem endret hva, når",
        helpEn: "Who changed what, when",
        profileNb: "Ikke synlig",
        profileEn: "Not visible",
        profileVisibility: "hidden",
        centerNb: "Full audit trail per endring",
        centerEn: "Full audit trail per change",
        centerVisibility: "center",
      },
    ],
  },
];
