project_id = "yyvadlijsovebszximjv"

[functions.analyze-document]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.suggest-assets]
verify_jwt = false

[functions.suggest-processes]
verify_jwt = false

[functions.suggest-deviations]
verify_jwt = false

[functions.fetch-7security-data]
verify_jwt = false

[functions.suggest-work-area-assets]
verify_jwt = false

[functions.analyze-vendor]
verify_jwt = false

[functions.push-vendor-incidents]
verify_jwt = false

[functions.classify-document]
verify_jwt = false

[functions.suggest-vendor-category]
verify_jwt = false

[functions.mynder-me-api]
verify_jwt = false

[functions.suggest-ai-purpose]
verify_jwt = false

[functions.suggest-company-description]
verify_jwt = false
