project_id = "yyvadlijsovebszximjv"

[functions.analyze-document]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.suggest-assets]
verify_jwt = false

[functions.suggest-processes]
verify_jwt = false
