// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list_vendors.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list_vendors.ts
var list_vendors_default = defineTool({
  name: "list_vendors",
  title: "List vendors",
  description: "List the registered vendors/assets in Mynder with their criticality, risk level, and category. Returns a compact JSON array.",
  inputSchema: {
    limit: z.number().min(1).max(100).default(20).describe("Maximum number of vendors to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assets").select("id, name, asset_type, criticality, risk_level, risk_score, category, vendor_category, gdpr_role, url, compliance_score, tprm_status").eq("asset_type", "vendor").order("name", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }] };
  }
});

// src/lib/mcp/tools/list_requirements.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_requirements_default = defineTool2({
  name: "list_requirements",
  title: "List requirements",
  description: "List compliance requirements and their articles from the frameworks that are currently activated in Mynder.",
  inputSchema: {
    framework_id: z2.string().optional().describe("Optional framework ID to filter requirements to a specific framework."),
    limit: z2.number().min(1).max(200).default(50).describe("Maximum number of requirements to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ framework_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("compliance_requirements").select("id, requirement_id, framework_id, name, name_no, description, description_no, domain, category, priority, is_active, is_relevant").eq("is_active", true).order("sort_order", { ascending: true }).limit(limit);
    if (framework_id) {
      query = query.eq("framework_id", framework_id);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }] };
  }
});

// src/lib/mcp/tools/get_documentation_status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_documentation_status_default = defineTool3({
  name: "get_documentation_status",
  title: "Get documentation status",
  description: "Return the documentation/maturity status for each activated framework, including how many requirements are covered and the overall maturity level.",
  inputSchema: {
    framework_id: z3.string().optional().describe("Optional framework ID to get status for a single framework.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ framework_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let selectedQuery = supabase.from("selected_frameworks").select("framework_id, framework_name, category, is_selected").eq("is_selected", true);
    if (framework_id) {
      selectedQuery = selectedQuery.eq("framework_id", framework_id);
    }
    const { data: frameworks, error: fwError } = await selectedQuery;
    if (fwError) {
      return { content: [{ type: "text", text: fwError.message }], isError: true };
    }
    if (!frameworks || frameworks.length === 0) {
      return { content: [{ type: "text", text: "No frameworks are currently activated." }] };
    }
    const ids = frameworks.map((f) => f.framework_id);
    const { data: requirements, error: reqError } = await supabase.from("compliance_requirements").select("id, framework_id, name, name_no").in("framework_id", ids).eq("is_active", true);
    if (reqError) {
      return { content: [{ type: "text", text: reqError.message }], isError: true };
    }
    const reqIds = (requirements ?? []).map((r) => r.id);
    const { data: statuses, error: statusError } = await supabase.from("requirement_status").select("requirement_id, status, maturity_level, progress_percent, evidence_notes").in("requirement_id", reqIds);
    if (statusError) {
      return { content: [{ type: "text", text: statusError.message }], isError: true };
    }
    const statusMap = new Map((statuses ?? []).map((s) => [s.requirement_id, s]));
    const result = frameworks.map((fw) => {
      const fwReqs = (requirements ?? []).filter((r) => r.framework_id === fw.framework_id);
      const fwStatuses = fwReqs.map((r) => statusMap.get(r.id) ?? null);
      const total = fwReqs.length;
      const covered = fwStatuses.filter((s) => s && (s.status === "fulfilled" || s.status === "complete" || s.status === "yes" || (s.progress_percent ?? 0) >= 100)).length;
      const inProgress = fwStatuses.filter((s) => s && (s.status === "in_progress" || (s.progress_percent ?? 0) > 0 && (s.progress_percent ?? 0) < 100)).length;
      const notStarted = total - covered - inProgress;
      const avgMaturity = fwStatuses.length > 0 ? Math.round(fwStatuses.reduce((sum, s) => sum + (s?.maturity_level ?? 0), 0) / fwStatuses.length) : 0;
      return {
        framework_id: fw.framework_id,
        framework_name: fw.framework_name,
        category: fw.category,
        total_requirements: total,
        covered,
        in_progress: inProgress,
        not_started: notStarted,
        average_maturity_level: avgMaturity
      };
    });
    return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
  }
});

// src/lib/mcp/tools/create_activity.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_activity_default = defineTool4({
  name: "create_activity",
  title: "Create activity",
  description: "Create a user task/activity in Mynder, typically tied to a vendor or follow-up item.",
  inputSchema: {
    title: z4.string().trim().min(1).max(200).describe("Title of the activity."),
    description: z4.string().trim().max(2e3).optional().describe("Optional description of the activity."),
    asset_id: z4.string().uuid().optional().describe("Optional asset/vendor ID to link the activity to."),
    due_date: z4.string().datetime().optional().describe("Optional due date in ISO 8601 format.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false, destructiveHint: false },
  handler: async ({ title, description, asset_id, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_tasks").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      asset_id: asset_id ?? null,
      due_date: due_date ?? null,
      status: "open"
    }).select("id, title, description, asset_id, due_date, status, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/report_document_coverage.ts
import { defineTool as defineTool5, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var coverageSchema = z5.object({
  article_id: z5.string().min(1).describe("Identifier of the article/requirement article covered by the document."),
  covered: z5.boolean().describe("Whether the article is covered by the document.")
});
var report_document_coverage_default = defineTool5({
  name: "report_document_coverage",
  title: "Report document coverage",
  description: "Report how many articles in a requirement are covered by a document found in the caller's own infrastructure. This updates the requirement maturity/progress in Mynder without uploading the actual document.",
  inputSchema: {
    requirement_id: z5.string().min(1).describe("Mynder requirement ID to update."),
    coverage: z5.array(coverageSchema).min(1).describe("Array of article coverage results."),
    notes: z5.string().max(2e3).optional().describe("Optional notes about the document or coverage assessment.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false, destructiveHint: false },
  handler: async ({ requirement_id, coverage, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: req, error: reqError } = await supabase.from("compliance_requirements").select("id, framework_id, name, is_active").eq("id", requirement_id).single();
    if (reqError || !req) {
      throw new ToolError(`Requirement ${requirement_id} not found or not accessible.`);
    }
    if (!req.is_active) {
      throw new ToolError(`Requirement ${requirement_id} is not active and cannot be updated.`);
    }
    const coveredCount = coverage.filter((c) => c.covered).length;
    const totalCount = coverage.length;
    const progressPercent = totalCount === 0 ? 0 : Math.round(coveredCount / totalCount * 100);
    const maturityLevel = progressPercent >= 75 ? 3 : progressPercent >= 50 ? 2 : progressPercent > 0 ? 1 : 0;
    const status = progressPercent >= 100 ? "fulfilled" : progressPercent > 0 ? "in_progress" : "not_started";
    const { data: existing, error: existingError } = await supabase.from("requirement_status").select("id").eq("requirement_id", requirement_id).maybeSingle();
    if (existingError) {
      return { content: [{ type: "text", text: existingError.message }], isError: true };
    }
    const payload = {
      requirement_id,
      status,
      maturity_level: maturityLevel,
      progress_percent: progressPercent,
      evidence_notes: notes ? `${notes}

Coverage: ${coveredCount}/${totalCount} articles covered.` : `Coverage: ${coveredCount}/${totalCount} articles covered.`,
      updated_at: (/* @__PURE__ */ new Date()).toISOString(),
      completed_at: progressPercent >= 100 ? (/* @__PURE__ */ new Date()).toISOString() : null
    };
    let result;
    if (existing?.id) {
      const { data, error } = await supabase.from("requirement_status").update(payload).eq("id", existing.id).select().single();
      result = { data, error };
    } else {
      const { data, error } = await supabase.from("requirement_status").insert({ ...payload, created_at: (/* @__PURE__ */ new Date()).toISOString() }).select().single();
      result = { data, error };
    }
    if (result.error) {
      return { content: [{ type: "text", text: result.error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Updated requirement "${req.name}" (${requirement_id}). Coverage: ${coveredCount}/${totalCount} articles (${progressPercent}%). Maturity level: ${maturityLevel}.`
        }
      ]
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yyvadlijsovebszximjv";
var mcp_default = defineMcp({
  name: "mynder-core",
  title: "Mynder Core",
  version: "0.1.0",
  instructions: "Mynder Core MCP server exposes vendor, compliance, and documentation tools. Use list_vendors to see registered vendors and their criticality. Use list_requirements to see active compliance requirements. Use get_documentation_status to see maturity per activated framework. Use create_activity to create a follow-up task. Use report_document_coverage to report how many articles a document in your own infrastructure covers, without uploading the document to Mynder.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_vendors_default, list_requirements_default, get_documentation_status_default, create_activity_default, report_document_coverage_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
